package de.corespace.shroud.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

// GENERATED by app/src/test/java/de/corespace/shroud/ui/theme/gen_shroud_icons.py — do not edit by
// hand; add icons to the script's list and run it (00-plan §1.7.12, W1-UI-THEME).

/**
 * The icons `design/Android-App.pen` uses, as the design names them: Lucide (24-unit, 2-unit round
 * stroke; ISC) and Phosphor (256-unit fills; MIT), the union the area specs ask for (00-plan
 * §1.7.12: shell-chats §15.2, conversation-thread §23.4, conversation-compose-media §2.5, calls
 * §13.3, contacts §7.2, settings-lock §2/§11, notifications, design-inventory §2). Generated from
 * lucide-static 1.49.0 and @phosphor-icons/core 2.1.1: each path is the SVG's own, so the
 * glyphs match the frames. iOS draws SF Symbols instead; the design chose these equivalents.
 *
 * Naming: PascalCase of the design name. Where both libraries have the same name, Lucide keeps the
 * plain name and the Phosphor regular weight takes a `Regular` suffix ([Globe] is Lucide,
 * [GlobeRegular] is Phosphor). Every icon is listed in `assets/licenses/icons.txt`.
 *
 * Draw them with [de.corespace.shroud.ui.components.ShroudIcon], which tints them. Each vector is
 * built on first use.
 */
object ShroudIcons {
    /** Lucide `arrow-down-to-line`. */
    val ArrowDownToLine: ImageVector by lazy {
        icon("ArrowDownToLine", 24f, true,
        "M12 17V3",
        "m6 11 6 6 6-6",
        "M19 21H5")
    }

    /** Lucide `arrow-right`. */
    val ArrowRight: ImageVector by lazy {
        icon("ArrowRight", 24f, true,
        "M5 12h14",
        "m12 5 7 7-7 7")
    }

    /** Lucide `arrow-up`. */
    val ArrowUp: ImageVector by lazy {
        icon("ArrowUp", 24f, true,
        "m5 12 7-7 7 7",
        "M12 19V5")
    }

    /** Lucide `arrow-up-to-line`. */
    val ArrowUpToLine: ImageVector by lazy {
        icon("ArrowUpToLine", 24f, true,
        "M5 3h14",
        "m18 13-6-6-6 6",
        "M12 7v14")
    }

    /** Lucide `at-sign`. */
    val AtSign: ImageVector by lazy {
        icon("AtSign", 24f, true,
        "M8.0,12.0a4.0,4.0 0 1,0 8.0,0a4.0,4.0 0 1,0 -8.0,0",
        "M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8")
    }

    /** Lucide `audio-lines`. */
    val AudioLines: ImageVector by lazy {
        icon("AudioLines", 24f, true,
        "M2 10v3",
        "M6 6v11",
        "M10 3v18",
        "M14 8v7",
        "M18 5v13",
        "M22 10v3")
    }

    /** Lucide `bell`. */
    val Bell: ImageVector by lazy {
        icon("Bell", 24f, true,
        "M10.268 21a2 2 0 0 0 3.464 0",
        "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326")
    }

    /** Lucide `camera`. */
    val Camera: ImageVector by lazy {
        icon("Camera", 24f, true,
        "M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z",
        "M9.0,13.0a3.0,3.0 0 1,0 6.0,0a3.0,3.0 0 1,0 -6.0,0")
    }

    /** Lucide `camera-off`. */
    val CameraOff: ImageVector by lazy {
        icon("CameraOff", 24f, true,
        "M14.564 14.558a3 3 0 1 1-4.122-4.121",
        "m2 2 20 20",
        "M20 20H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 .819-.175",
        "M9.695 4.024A2 2 0 0 1 10.004 4h3.993a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v7.344")
    }

    /** Lucide `check`. */
    val Check: ImageVector by lazy {
        icon("Check", 24f, true,
        "M20 6 9 17l-5-5")
    }

    /** Lucide `check-check`. */
    val CheckCheck: ImageVector by lazy {
        icon("CheckCheck", 24f, true,
        "M18 6 7 17l-5-5",
        "m22 10-7.5 7.5L13 16")
    }

    /** Lucide `chevron-down`. */
    val ChevronDown: ImageVector by lazy {
        icon("ChevronDown", 24f, true,
        "m6 9 6 6 6-6")
    }

    /** Lucide `chevron-left`. */
    val ChevronLeft: ImageVector by lazy {
        icon("ChevronLeft", 24f, true,
        "m15 18-6-6 6-6")
    }

    /** Lucide `chevron-right`. */
    val ChevronRight: ImageVector by lazy {
        icon("ChevronRight", 24f, true,
        "m9 18 6-6-6-6")
    }

    /** Lucide `chevron-up`. */
    val ChevronUp: ImageVector by lazy {
        icon("ChevronUp", 24f, true,
        "m18 15-6-6-6 6")
    }

    /** Lucide `chevrons-up-down`. */
    val ChevronsUpDown: ImageVector by lazy {
        icon("ChevronsUpDown", 24f, true,
        "m7 15 5 5 5-5",
        "m7 9 5-5 5 5")
    }

    /** Lucide `circle`. */
    val Circle: ImageVector by lazy {
        icon("Circle", 24f, true,
        "M2.0,12.0a10.0,10.0 0 1,0 20.0,0a10.0,10.0 0 1,0 -20.0,0")
    }

    /** Lucide `circle-check`. */
    val CircleCheck: ImageVector by lazy {
        icon("CircleCheck", 24f, true,
        "M2.0,12.0a10.0,10.0 0 1,0 20.0,0a10.0,10.0 0 1,0 -20.0,0",
        "m16 9-5.5 5.5L8 12")
    }

    /** Lucide `clipboard`. */
    val Clipboard: ImageVector by lazy {
        icon("Clipboard", 24f, true,
        "M9.0,2.0h6.0a1.0,1.0 0 0 1 1.0,1.0v2.0a1.0,1.0 0 0 1 -1.0,1.0h-6.0a1.0,1.0 0 0 1 -1.0,-1.0v-2.0a1.0,1.0 0 0 1 1.0,-1.0z",
        "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2")
    }

    /** Lucide `copy`. */
    val Copy: ImageVector by lazy {
        icon("Copy", 24f, true,
        "M10.0,8.0h10.0a2.0,2.0 0 0 1 2.0,2.0v10.0a2.0,2.0 0 0 1 -2.0,2.0h-10.0a2.0,2.0 0 0 1 -2.0,-2.0v-10.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2")
    }

    /** Lucide `download`. */
    val Download: ImageVector by lazy {
        icon("Download", 24f, true,
        "M12 15V3",
        "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
        "m7 10 5 5 5-5")
    }

    /** Lucide `ellipsis`. */
    val Ellipsis: ImageVector by lazy {
        icon("Ellipsis", 24f, true,
        "M11.0,12.0a1.0,1.0 0 1,0 2.0,0a1.0,1.0 0 1,0 -2.0,0",
        "M18.0,12.0a1.0,1.0 0 1,0 2.0,0a1.0,1.0 0 1,0 -2.0,0",
        "M4.0,12.0a1.0,1.0 0 1,0 2.0,0a1.0,1.0 0 1,0 -2.0,0")
    }

    /** Lucide `eye`. */
    val Eye: ImageVector by lazy {
        icon("Eye", 24f, true,
        "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
        "M9.0,12.0a3.0,3.0 0 1,0 6.0,0a3.0,3.0 0 1,0 -6.0,0")
    }

    /** Lucide `eye-off`. */
    val EyeOff: ImageVector by lazy {
        icon("EyeOff", 24f, true,
        "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
        "M14.084 14.158a3 3 0 0 1-4.242-4.242",
        "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
        "m2 2 20 20")
    }

    /** Lucide `flip-horizontal-2`. */
    val FlipHorizontal2: ImageVector by lazy {
        icon("FlipHorizontal2", 24f, true,
        "M10 12H8",
        "M16 12h-2",
        "M22 12h-2",
        "M4 12H2",
        "M7.298 20.288A1 1 0 008 22h8a1 1 0 00.703-1.712l-3.991-3.99a1 1 0 00-1.424-.001z",
        "M7.298 3.712A1 1 0 018 2h8a1 1 0 01.703 1.712l-3.991 3.99a1 1 0 01-1.424.001z")
    }

    /** Lucide `folder`. */
    val Folder: ImageVector by lazy {
        icon("Folder", 24f, true,
        "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z")
    }

    /** Lucide `forward`. */
    val Forward: ImageVector by lazy {
        icon("Forward", 24f, true,
        "m15 17 5-5-5-5",
        "M4 18v-2a4 4 0 0 1 4-4h12")
    }

    /** Lucide `globe`. */
    val Globe: ImageVector by lazy {
        icon("Globe", 24f, true,
        "M2.0,12.0a10.0,10.0 0 1,0 20.0,0a10.0,10.0 0 1,0 -20.0,0",
        "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",
        "M2 12h20")
    }

    /** Lucide `hand`. */
    val Hand: ImageVector by lazy {
        icon("Hand", 24f, true,
        "M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2",
        "M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2",
        "M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8",
        "M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15")
    }

    /** Lucide `hash`. */
    val Hash: ImageVector by lazy {
        icon("Hash", 24f, true,
        "M4.0,9.0L20.0,9.0",
        "M4.0,15.0L20.0,15.0",
        "M10.0,3.0L8.0,21.0",
        "M16.0,3.0L14.0,21.0")
    }

    /** Lucide `image`. */
    val Image: ImageVector by lazy {
        icon("Image", 24f, true,
        "M5.0,3.0h14.0a2.0,2.0 0 0 1 2.0,2.0v14.0a2.0,2.0 0 0 1 -2.0,2.0h-14.0a2.0,2.0 0 0 1 -2.0,-2.0v-14.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M7.0,9.0a2.0,2.0 0 1,0 4.0,0a2.0,2.0 0 1,0 -4.0,0",
        "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21")
    }

    /** Lucide `images`. */
    val Images: ImageVector by lazy {
        icon("Images", 24f, true,
        "m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16",
        "M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2",
        "M12.0,7.0a1.0,1.0 0 1,0 2.0,0a1.0,1.0 0 1,0 -2.0,0",
        "M10.0,2.0h10.0a2.0,2.0 0 0 1 2.0,2.0v10.0a2.0,2.0 0 0 1 -2.0,2.0h-10.0a2.0,2.0 0 0 1 -2.0,-2.0v-10.0a2.0,2.0 0 0 1 2.0,-2.0z")
    }

    /** Lucide `info`. */
    val Info: ImageVector by lazy {
        icon("Info", 24f, true,
        "M2.0,12.0a10.0,10.0 0 1,0 20.0,0a10.0,10.0 0 1,0 -20.0,0",
        "M12 16v-4",
        "M12 8h.01")
    }

    /** Lucide `key-round`. */
    val KeyRound: ImageVector by lazy {
        icon("KeyRound", 24f, true,
        "M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z",
        "M16.0,7.5a0.5,0.5 0 1,0 1.0,0a0.5,0.5 0 1,0 -1.0,0")
    }

    /** Lucide `link`. */
    val Link: ImageVector by lazy {
        icon("Link", 24f, true,
        "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71",
        "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71")
    }

    /** Lucide `list`. */
    val List: ImageVector by lazy {
        icon("List", 24f, true,
        "M3 5h.01",
        "M3 12h.01",
        "M3 19h.01",
        "M8 5h13",
        "M8 12h13",
        "M8 19h13")
    }

    /** Lucide `loader-circle`. */
    val LoaderCircle: ImageVector by lazy {
        icon("LoaderCircle", 24f, true,
        "M21 12a9 9 0 1 1-6.219-8.56")
    }

    /** Lucide `lock`. */
    val Lock: ImageVector by lazy {
        icon("Lock", 24f, true,
        "M5.0,11.0h14.0a2.0,2.0 0 0 1 2.0,2.0v7.0a2.0,2.0 0 0 1 -2.0,2.0h-14.0a2.0,2.0 0 0 1 -2.0,-2.0v-7.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M7 11V7a5 5 0 0 1 10 0v4")
    }

    /** Lucide `lock-keyhole`. */
    val LockKeyhole: ImageVector by lazy {
        icon("LockKeyhole", 24f, true,
        "M11.0,16.0a1.0,1.0 0 1,0 2.0,0a1.0,1.0 0 1,0 -2.0,0",
        "M5.0,10.0h14.0a2.0,2.0 0 0 1 2.0,2.0v8.0a2.0,2.0 0 0 1 -2.0,2.0h-14.0a2.0,2.0 0 0 1 -2.0,-2.0v-8.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M7 10V7a5 5 0 0 1 10 0v3")
    }

    /** Lucide `lock-open`. */
    val LockOpen: ImageVector by lazy {
        icon("LockOpen", 24f, true,
        "M5.0,11.0h14.0a2.0,2.0 0 0 1 2.0,2.0v7.0a2.0,2.0 0 0 1 -2.0,2.0h-14.0a2.0,2.0 0 0 1 -2.0,-2.0v-7.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M7 11V7a5 5 0 0 1 9.9-1")
    }

    /** Lucide `maximize-2`. */
    val Maximize2: ImageVector by lazy {
        icon("Maximize2", 24f, true,
        "M15 3h6v6",
        "m21 3-7 7",
        "m3 21 7-7",
        "M9 21H3v-6")
    }

    /** Lucide `mic`. */
    val Mic: ImageVector by lazy {
        icon("Mic", 24f, true,
        "M12 19v3",
        "M19 10v2a7 7 0 0 1-14 0v-2",
        "M12.0,2.0h0.0a3.0,3.0 0 0 1 3.0,3.0v7.0a3.0,3.0 0 0 1 -3.0,3.0h-0.0a3.0,3.0 0 0 1 -3.0,-3.0v-7.0a3.0,3.0 0 0 1 3.0,-3.0z")
    }

    /** Lucide `mic-off`. */
    val MicOff: ImageVector by lazy {
        icon("MicOff", 24f, true,
        "M12 19v3",
        "M15 9.34V5a3 3 0 0 0-5.68-1.33",
        "M16.95 16.95A7 7 0 0 1 5 12v-2",
        "M18.89 13.23A7 7 0 0 0 19 12v-2",
        "m2 2 20 20",
        "M9 9v3a3 3 0 0 0 5.12 2.12")
    }

    /** Lucide `minimize-2`. */
    val Minimize2: ImageVector by lazy {
        icon("Minimize2", 24f, true,
        "m14 10 7-7",
        "M20 10h-6V4",
        "m3 21 7-7",
        "M4 14h6v6")
    }

    /** Lucide `monitor-smartphone`. */
    val MonitorSmartphone: ImageVector by lazy {
        icon("MonitorSmartphone", 24f, true,
        "M18 8V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h8",
        "M10 19v-3.96 3.15",
        "M7 19h5",
        "M18.0,12.0h2.0a2.0,2.0 0 0 1 2.0,2.0v6.0a2.0,2.0 0 0 1 -2.0,2.0h-2.0a2.0,2.0 0 0 1 -2.0,-2.0v-6.0a2.0,2.0 0 0 1 2.0,-2.0z")
    }

    /** Lucide `pencil`. */
    val Pencil: ImageVector by lazy {
        icon("Pencil", 24f, true,
        "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
        "m15 5 4 4")
    }

    /** Lucide `phone`. */
    val Phone: ImageVector by lazy {
        icon("Phone", 24f, true,
        "M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384")
    }

    /** Lucide `phone-off`. */
    val PhoneOff: ImageVector by lazy {
        icon("PhoneOff", 24f, true,
        "M10.1 13.9a14 14 0 0 0 3.732 2.668 1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2 18 18 0 0 1-12.728-5.272",
        "M22 2 2 22",
        "M4.76 13.582A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 .244.473")
    }

    /** Lucide `pin`. */
    val Pin: ImageVector by lazy {
        icon("Pin", 24f, true,
        "M12 17v5",
        "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z")
    }

    /** Lucide `play`. */
    val Play: ImageVector by lazy {
        icon("Play", 24f, true,
        "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z")
    }

    /** Lucide `plus`. */
    val Plus: ImageVector by lazy {
        icon("Plus", 24f, true,
        "M5 12h14",
        "M12 5v14")
    }

    /** Lucide `qr-code`. */
    val QrCode: ImageVector by lazy {
        icon("QrCode", 24f, true,
        "M4.0,3.0h3.0a1.0,1.0 0 0 1 1.0,1.0v3.0a1.0,1.0 0 0 1 -1.0,1.0h-3.0a1.0,1.0 0 0 1 -1.0,-1.0v-3.0a1.0,1.0 0 0 1 1.0,-1.0z",
        "M17.0,3.0h3.0a1.0,1.0 0 0 1 1.0,1.0v3.0a1.0,1.0 0 0 1 -1.0,1.0h-3.0a1.0,1.0 0 0 1 -1.0,-1.0v-3.0a1.0,1.0 0 0 1 1.0,-1.0z",
        "M4.0,16.0h3.0a1.0,1.0 0 0 1 1.0,1.0v3.0a1.0,1.0 0 0 1 -1.0,1.0h-3.0a1.0,1.0 0 0 1 -1.0,-1.0v-3.0a1.0,1.0 0 0 1 1.0,-1.0z",
        "M21 16h-3a2 2 0 0 0-2 2v3",
        "M21 21v.01",
        "M12 7v3a2 2 0 0 1-2 2H7",
        "M3 12h.01",
        "M12 3h.01",
        "M12 16v.01",
        "M16 12h1",
        "M21 12v.01",
        "M12 21v-1")
    }

    /** Lucide `refresh-cw`. */
    val RefreshCw: ImageVector by lazy {
        icon("RefreshCw", 24f, true,
        "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
        "M21 3v5h-5",
        "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
        "M8 16H3v5")
    }

    /** Lucide `reply`. */
    val Reply: ImageVector by lazy {
        icon("Reply", 24f, true,
        "M20 18v-2a4 4 0 0 0-4-4H4",
        "m9 17-5-5 5-5")
    }

    /** Lucide `rotate-ccw`. */
    val RotateCcw: ImageVector by lazy {
        icon("RotateCcw", 24f, true,
        "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
        "M3 3v5h5")
    }

    /** Lucide `rotate-ccw-square`. */
    val RotateCcwSquare: ImageVector by lazy {
        icon("RotateCcwSquare", 24f, true,
        "M20 9V7a2 2 0 0 0-2-2h-6",
        "m15 2-3 3 3 3",
        "M20 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h2")
    }

    /** Lucide `scan`. */
    val Scan: ImageVector by lazy {
        icon("Scan", 24f, true,
        "M3 7V5a2 2 0 0 1 2-2h2",
        "M17 3h2a2 2 0 0 1 2 2v2",
        "M21 17v2a2 2 0 0 1-2 2h-2",
        "M7 21H5a2 2 0 0 1-2-2v-2")
    }

    /** Lucide `scan-face`. */
    val ScanFace: ImageVector by lazy {
        icon("ScanFace", 24f, true,
        "M3 7V5a2 2 0 0 1 2-2h2",
        "M17 3h2a2 2 0 0 1 2 2v2",
        "M21 17v2a2 2 0 0 1-2 2h-2",
        "M7 21H5a2 2 0 0 1-2-2v-2",
        "M8 14s1.5 2 4 2 4-2 4-2",
        "M9 9h.01",
        "M15 9h.01")
    }

    /** Lucide `scan-text`. */
    val ScanText: ImageVector by lazy {
        icon("ScanText", 24f, true,
        "M3 7V5a2 2 0 0 1 2-2h2",
        "M17 3h2a2 2 0 0 1 2 2v2",
        "M21 17v2a2 2 0 0 1-2 2h-2",
        "M7 21H5a2 2 0 0 1-2-2v-2",
        "M7 8h8",
        "M7 12h10",
        "M7 16h6")
    }

    /** Lucide `screen-share`. */
    val ScreenShare: ImageVector by lazy {
        icon("ScreenShare", 24f, true,
        "M13 3H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-3",
        "M8 21h8",
        "M12 17v4",
        "m17 8 5-5",
        "M17 3h5v5")
    }

    /** Lucide `search`. */
    val Search: ImageVector by lazy {
        icon("Search", 24f, true,
        "m21 21-4.34-4.34",
        "M3.0,11.0a8.0,8.0 0 1,0 16.0,0a8.0,8.0 0 1,0 -16.0,0")
    }

    /** Lucide `share-2`. */
    val Share2: ImageVector by lazy {
        icon("Share2", 24f, true,
        "M15.0,5.0a3.0,3.0 0 1,0 6.0,0a3.0,3.0 0 1,0 -6.0,0",
        "M3.0,12.0a3.0,3.0 0 1,0 6.0,0a3.0,3.0 0 1,0 -6.0,0",
        "M15.0,19.0a3.0,3.0 0 1,0 6.0,0a3.0,3.0 0 1,0 -6.0,0",
        "M8.59,13.51L15.42,17.49",
        "M15.41,6.51L8.59,10.49")
    }

    /** Lucide `shield`. */
    val Shield: ImageVector by lazy {
        icon("Shield", 24f, true,
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z")
    }

    /** Lucide `shield-alert`. */
    val ShieldAlert: ImageVector by lazy {
        icon("ShieldAlert", 24f, true,
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
        "M12 8v4",
        "M12 16h.01")
    }

    /** Lucide `shield-check`. */
    val ShieldCheck: ImageVector by lazy {
        icon("ShieldCheck", 24f, true,
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
        "m9 12 2 2 4-4")
    }

    /** Lucide `shield-half`. */
    val ShieldHalf: ImageVector by lazy {
        icon("ShieldHalf", 24f, true,
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
        "M12 22V2")
    }

    /** Lucide `smartphone`. */
    val Smartphone: ImageVector by lazy {
        icon("Smartphone", 24f, true,
        "M7.0,2.0h10.0a2.0,2.0 0 0 1 2.0,2.0v16.0a2.0,2.0 0 0 1 -2.0,2.0h-10.0a2.0,2.0 0 0 1 -2.0,-2.0v-16.0a2.0,2.0 0 0 1 2.0,-2.0z",
        "M12 18h.01")
    }

    /** Lucide `smile`. */
    val Smile: ImageVector by lazy {
        icon("Smile", 24f, true,
        "M15 10V9",
        "M16.472 15a6 6 0 01-8.943 0",
        "M9 10V9",
        "M2.0,12.0a10.0,10.0 0 1,0 20.0,0a10.0,10.0 0 1,0 -20.0,0")
    }

    /** Lucide `square-pen`. */
    val SquarePen: ImageVector by lazy {
        icon("SquarePen", 24f, true,
        "M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7",
        "M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z")
    }

    /** Lucide `trash-2`. */
    val Trash2: ImageVector by lazy {
        icon("Trash2", 24f, true,
        "M10 11v6",
        "M14 11v6",
        "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6",
        "M3 6h18",
        "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2")
    }

    /** Lucide `triangle-alert`. */
    val TriangleAlert: ImageVector by lazy {
        icon("TriangleAlert", 24f, true,
        "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
        "M12 9v4",
        "M12 17h.01")
    }

    /** Lucide `user-plus`. */
    val UserPlus: ImageVector by lazy {
        icon("UserPlus", 24f, true,
        "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2",
        "M5.0,7.0a4.0,4.0 0 1,0 8.0,0a4.0,4.0 0 1,0 -8.0,0",
        "M19.0,8.0L19.0,14.0",
        "M22.0,11.0L16.0,11.0")
    }

    /** Lucide `video`. */
    val Video: ImageVector by lazy {
        icon("Video", 24f, true,
        "m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5",
        "M4.0,6.0h10.0a2.0,2.0 0 0 1 2.0,2.0v8.0a2.0,2.0 0 0 1 -2.0,2.0h-10.0a2.0,2.0 0 0 1 -2.0,-2.0v-8.0a2.0,2.0 0 0 1 2.0,-2.0z")
    }

    /** Lucide `video-off`. */
    val VideoOff: ImageVector by lazy {
        icon("VideoOff", 24f, true,
        "M10.66 6H14a2 2 0 0 1 2 2v2.5l5.248-3.062A.5.5 0 0 1 22 7.87v8.196",
        "M16 16a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2",
        "m2 2 20 20")
    }

    /** Lucide `volume-2`. */
    val Volume2: ImageVector by lazy {
        icon("Volume2", 24f, true,
        "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z",
        "M16 9a5 5 0 0 1 0 6",
        "M19.364 18.364a9 9 0 0 0 0-12.728")
    }

    /** Lucide `wifi-off`. */
    val WifiOff: ImageVector by lazy {
        icon("WifiOff", 24f, true,
        "M12 20h.01",
        "M8.5 16.429a5 5 0 0 1 7 0",
        "M5 12.859a10 10 0 0 1 5.17-2.69",
        "M19 12.859a10 10 0 0 0-2.007-1.523",
        "M2 8.82a15 15 0 0 1 4.177-2.643",
        "M22 8.82a15 15 0 0 0-11.288-3.764",
        "m2 2 20 20")
    }

    /** Lucide `x`. */
    val X: ImageVector by lazy {
        icon("X", 24f, true,
        "M18 6 6 18",
        "m6 6 12 12")
    }

    /** Phosphor `arrow-bend-up-left`. */
    val ArrowBendUpLeft: ImageVector by lazy {
        icon("ArrowBendUpLeft", 256f, false,
        "M232,200a8,8,0,0,1-16,0,88.1,88.1,0,0,0-88-88H51.31l34.35,34.34a8,8,0,0,1-11.32,11.32l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,85.66,61.66L51.31,96H128A104.11,104.11,0,0,1,232,200Z")
    }

    /** Phosphor `arrow-bend-up-left-fill`. */
    val ArrowBendUpLeftFill: ImageVector by lazy {
        icon("ArrowBendUpLeftFill", 256f, false,
        "M232,200a8,8,0,0,1-16,0,88.1,88.1,0,0,0-88-88H88v40a8,8,0,0,1-13.66,5.66l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,88,56V96h40A104.11,104.11,0,0,1,232,200Z")
    }

    /** Phosphor `arrow-bend-up-right`. */
    val ArrowBendUpRight: ImageVector by lazy {
        icon("ArrowBendUpRight", 256f, false,
        "M229.66,109.66l-48,48a8,8,0,0,1-11.32-11.32L204.69,112H128a88.1,88.1,0,0,0-88,88,8,8,0,0,1-16,0A104.11,104.11,0,0,1,128,96h76.69L170.34,61.66a8,8,0,0,1,11.32-11.32l48,48A8,8,0,0,1,229.66,109.66Z")
    }

    /** Phosphor `arrow-clockwise-bold`. */
    val ArrowClockwiseBold: ImageVector by lazy {
        icon("ArrowClockwiseBold", 256f, false,
        "M244,56v48a12,12,0,0,1-12,12H184a12,12,0,1,1,0-24H201.1l-19-17.38c-.13-.12-.26-.24-.38-.37A76,76,0,1,0,127,204h1a75.53,75.53,0,0,0,52.15-20.72,12,12,0,0,1,16.49,17.45A99.45,99.45,0,0,1,128,228h-1.37A100,100,0,1,1,198.51,57.06L220,76.72V56a12,12,0,0,1,24,0Z")
    }

    /** Phosphor `arrow-down-bold`. */
    val ArrowDownBold: ImageVector by lazy {
        icon("ArrowDownBold", 256f, false,
        "M208.49,152.49l-72,72a12,12,0,0,1-17,0l-72-72a12,12,0,0,1,17-17L116,187V40a12,12,0,0,1,24,0V187l51.51-51.52a12,12,0,0,1,17,17Z")
    }

    /** Phosphor `arrow-down-left-bold`. */
    val ArrowDownLeftBold: ImageVector by lazy {
        icon("ArrowDownLeftBold", 256f, false,
        "M200.49,72.48,93,180h75a12,12,0,0,1,0,24H64a12,12,0,0,1-12-12V88a12,12,0,0,1,24,0v75L183.51,55.51a12,12,0,0,1,17,17Z")
    }

    /** Phosphor `arrow-right-bold`. */
    val ArrowRightBold: ImageVector by lazy {
        icon("ArrowRightBold", 256f, false,
        "M224.49,136.49l-72,72a12,12,0,0,1-17-17L187,140H40a12,12,0,0,1,0-24H187L135.51,64.48a12,12,0,0,1,17-17l72,72A12,12,0,0,1,224.49,136.49Z")
    }

    /** Phosphor `arrow-u-up-left`. */
    val ArrowUUpLeft: ImageVector by lazy {
        icon("ArrowUUpLeft", 256f, false,
        "M232,144a64.07,64.07,0,0,1-64,64H80a8,8,0,0,1,0-16h88a48,48,0,0,0,0-96H51.31l34.35,34.34a8,8,0,0,1-11.32,11.32l-48-48a8,8,0,0,1,0-11.32l48-48A8,8,0,0,1,85.66,45.66L51.31,80H168A64.07,64.07,0,0,1,232,144Z")
    }

    /** Phosphor `arrow-up-bold`. */
    val ArrowUpBold: ImageVector by lazy {
        icon("ArrowUpBold", 256f, false,
        "M208.49,120.49a12,12,0,0,1-17,0L140,69V216a12,12,0,0,1-24,0V69L64.49,120.49a12,12,0,0,1-17-17l72-72a12,12,0,0,1,17,0l72,72A12,12,0,0,1,208.49,120.49Z")
    }

    /** Phosphor `arrow-up-right-bold`. */
    val ArrowUpRightBold: ImageVector by lazy {
        icon("ArrowUpRightBold", 256f, false,
        "M204,64V168a12,12,0,0,1-24,0V93L72.49,200.49a12,12,0,0,1-17-17L163,76H88a12,12,0,0,1,0-24H192A12,12,0,0,1,204,64Z")
    }

    /** Phosphor `battery-warning-fill`. */
    val BatteryWarningFill: ImageVector by lazy {
        icon("BatteryWarningFill", 256f, false,
        "M200,56H32A24,24,0,0,0,8,80v96a24,24,0,0,0,24,24H200a24,24,0,0,0,24-24V80A24,24,0,0,0,200,56ZM108,88a8,8,0,0,1,16,0v40a8,8,0,0,1-16,0Zm8,88a12,12,0,1,1,12-12A12,12,0,0,1,116,176ZM256,96v64a8,8,0,0,1-16,0V96a8,8,0,0,1,16,0Z")
    }

    /** Phosphor `bell-fill`. */
    val BellFill: ImageVector by lazy {
        icon("BellFill", 256f, false,
        "M221.8,175.94C216.25,166.38,208,139.33,208,104a80,80,0,1,0-160,0c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.81a40,40,0,0,0,78.38,0H208a16,16,0,0,0,13.8-24.06ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216Z")
    }

    /** Phosphor `bell`. */
    val BellRegular: ImageVector by lazy {
        icon("BellRegular", 256f, false,
        "M221.8,175.94C216.25,166.38,208,139.33,208,104a80,80,0,1,0-160,0c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.81a40,40,0,0,0,78.38,0H208a16,16,0,0,0,13.8-24.06ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216ZM48,184c7.7-13.24,16-43.92,16-80a64,64,0,1,1,128,0c0,36.05,8.28,66.73,16,80Z")
    }

    /** Phosphor `bell-ringing-fill`. */
    val BellRingingFill: ImageVector by lazy {
        icon("BellRingingFill", 256f, false,
        "M224,71.1a8,8,0,0,1-10.78-3.42,94.13,94.13,0,0,0-33.46-36.91,8,8,0,1,1,8.54-13.54,111.46,111.46,0,0,1,39.12,43.09A8,8,0,0,1,224,71.1ZM35.71,72a8,8,0,0,0,7.1-4.32A94.13,94.13,0,0,1,76.27,30.77a8,8,0,1,0-8.54-13.54A111.46,111.46,0,0,0,28.61,60.32,8,8,0,0,0,35.71,72Zm186.1,103.94A16,16,0,0,1,208,200H167.2a40,40,0,0,1-78.4,0H48a16,16,0,0,1-13.79-24.06C43.22,160.39,48,138.28,48,112a80,80,0,0,1,160,0C208,138.27,212.78,160.38,221.81,175.94ZM150.62,200H105.38a24,24,0,0,0,45.24,0Z")
    }

    /** Phosphor `bell-slash`. */
    val BellSlash: ImageVector by lazy {
        icon("BellSlash", 256f, false,
        "M53.92,34.62A8,8,0,1,0,42.08,45.38L58.82,63.8A79.59,79.59,0,0,0,48,104c0,35.34-8.26,62.38-13.81,71.94A16,16,0,0,0,48,200H88.8a40,40,0,0,0,78.4,0h15.44l19.44,21.38a8,8,0,1,0,11.84-10.76ZM128,216a24,24,0,0,1-22.62-16h45.24A24,24,0,0,1,128,216ZM48,184c7.7-13.24,16-43.92,16-80a63.65,63.65,0,0,1,6.26-27.62L168.09,184Zm166-4.73a8.13,8.13,0,0,1-2.93.55,8,8,0,0,1-7.44-5.08C196.35,156.19,192,129.75,192,104A64,64,0,0,0,96.43,48.31a8,8,0,0,1-7.9-13.91A80,80,0,0,1,208,104c0,35.35,8.05,58.59,10.52,64.88A8,8,0,0,1,214,179.25Z")
    }

    /** Phosphor `bell-slash-fill`. */
    val BellSlashFill: ImageVector by lazy {
        icon("BellSlashFill", 256f, false,
        "M221.84,192v0a1.85,1.85,0,0,1-3,.28L83.27,43.19a4,4,0,0,1,.8-6A79.55,79.55,0,0,1,129.17,24C173,24.66,207.8,61.1,208,104.92c.14,34.88,8.31,61.54,13.82,71A15.89,15.89,0,0,1,221.84,192Zm-7.92,18.62a8,8,0,0,1-11.85,10.76L182.62,200H167.16a40,40,0,0,1-78.41,0H47.91a15.78,15.78,0,0,1-13.59-7.59,16.42,16.42,0,0,1-.09-16.68c5.55-9.73,13.7-36.64,13.7-71.73A79.42,79.42,0,0,1,58.79,63.85L42,45.38A8,8,0,1,1,53.84,34.62ZM150.59,200H105.32a24,24,0,0,0,45.27,0Z")
    }

    /** Phosphor `bookmark-simple-fill`. */
    val BookmarkSimpleFill: ImageVector by lazy {
        icon("BookmarkSimpleFill", 256f, false,
        "M184,32H72A16,16,0,0,0,56,48V224a8,8,0,0,0,12.24,6.78L128,193.43l59.77,37.35A8,8,0,0,0,200,224V48A16,16,0,0,0,184,32Z")
    }

    /** Phosphor `camera-fill`. */
    val CameraFill: ImageVector by lazy {
        icon("CameraFill", 256f, false,
        "M208,56H180.28L166.65,35.56A8,8,0,0,0,160,32H96a8,8,0,0,0-6.65,3.56L75.71,56H48A24,24,0,0,0,24,80V192a24,24,0,0,0,24,24H208a24,24,0,0,0,24-24V80A24,24,0,0,0,208,56Zm-44,76a36,36,0,1,1-36-36A36,36,0,0,1,164,132Z")
    }

    /** Phosphor `camera-rotate-fill`. */
    val CameraRotateFill: ImageVector by lazy {
        icon("CameraRotateFill", 256f, false,
        "M208,56H180.28L166.65,35.56A8,8,0,0,0,160,32H96a8,8,0,0,0-6.65,3.56L75.71,56H48A24,24,0,0,0,24,80V192a24,24,0,0,0,24,24H208a24,24,0,0,0,24-24V80A24,24,0,0,0,208,56ZM156.81,166.4A48.21,48.21,0,0,1,96,163.77V168a8,8,0,0,1-16,0V144a8,8,0,0,1,8-8h24a8,8,0,0,1,0,16h-5.15a32.12,32.12,0,0,0,40.34,1.61,8,8,0,0,1,9.62,12.79ZM176,120a8,8,0,0,1-8,8H144a8,8,0,0,1,0-16h5.15a32.12,32.12,0,0,0-40.34-1.61A8,8,0,0,1,99.19,97.6,48.21,48.21,0,0,1,160,100.23V96a8,8,0,0,1,16,0Z")
    }

    /** Phosphor `caret-down-bold`. */
    val CaretDownBold: ImageVector by lazy {
        icon("CaretDownBold", 256f, false,
        "M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z")
    }

    /** Phosphor `caret-left`. */
    val CaretLeft: ImageVector by lazy {
        icon("CaretLeft", 256f, false,
        "M165.66,202.34a8,8,0,0,1-11.32,11.32l-80-80a8,8,0,0,1,0-11.32l80-80a8,8,0,0,1,11.32,11.32L91.31,128Z")
    }

    /** Phosphor `caret-left-bold`. */
    val CaretLeftBold: ImageVector by lazy {
        icon("CaretLeftBold", 256f, false,
        "M168.49,199.51a12,12,0,0,1-17,17l-80-80a12,12,0,0,1,0-17l80-80a12,12,0,0,1,17,17L97,128Z")
    }

    /** Phosphor `caret-right`. */
    val CaretRight: ImageVector by lazy {
        icon("CaretRight", 256f, false,
        "M181.66,133.66l-80,80a8,8,0,0,1-11.32-11.32L164.69,128,90.34,53.66a8,8,0,0,1,11.32-11.32l80,80A8,8,0,0,1,181.66,133.66Z")
    }

    /** Phosphor `caret-right-bold`. */
    val CaretRightBold: ImageVector by lazy {
        icon("CaretRightBold", 256f, false,
        "M184.49,136.49l-80,80a12,12,0,0,1-17-17L159,128,87.51,56.49a12,12,0,1,1,17-17l80,80A12,12,0,0,1,184.49,136.49Z")
    }

    /** Phosphor `caret-up-bold`. */
    val CaretUpBold: ImageVector by lazy {
        icon("CaretUpBold", 256f, false,
        "M216.49,168.49a12,12,0,0,1-17,0L128,97,56.49,168.49a12,12,0,0,1-17-17l80-80a12,12,0,0,1,17,0l80,80A12,12,0,0,1,216.49,168.49Z")
    }

    /** Phosphor `caret-up-down`. */
    val CaretUpDown: ImageVector by lazy {
        icon("CaretUpDown", 256f, false,
        "M181.66,170.34a8,8,0,0,1,0,11.32l-48,48a8,8,0,0,1-11.32,0l-48-48a8,8,0,0,1,11.32-11.32L128,212.69l42.34-42.35A8,8,0,0,1,181.66,170.34Zm-96-84.68L128,43.31l42.34,42.35a8,8,0,0,0,11.32-11.32l-48-48a8,8,0,0,0-11.32,0l-48,48A8,8,0,0,0,85.66,85.66Z")
    }

    /** Phosphor `cell-signal-slash-bold`. */
    val CellSignalSlashBold: ImageVector by lazy {
        icon("CellSignalSlashBold", 256f, false,
        "M92,152v48a12,12,0,0,1-24,0V152a12,12,0,0,1,24,0ZM40,180a12,12,0,0,0-12,12v8a12,12,0,0,0,24,0v-8A12,12,0,0,0,40,180Zm176.88,27.93-160-176A12,12,0,1,0,39.12,48.07L108,123.84V200a12,12,0,0,0,24,0V150.24l16,17.6V200a12,12,0,0,0,24,0v-5.76l27.12,29.83a12,12,0,0,0,17.76-16.14ZM160,115.74a12,12,0,0,0,12-12V72a12,12,0,0,0-24,0v31.74A12,12,0,0,0,160,115.74Zm40,44a12,12,0,0,0,12-12V32a12,12,0,0,0-24,0V147.74A12,12,0,0,0,200,159.74Z")
    }

    /** Phosphor `chat-circle-dots`. */
    val ChatCircleDots: ImageVector by lazy {
        icon("ChatCircleDots", 256f, false,
        "M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128ZM84,116a12,12,0,1,0,12,12A12,12,0,0,0,84,116Zm88,0a12,12,0,1,0,12,12A12,12,0,0,0,172,116Zm60,12A104,104,0,0,1,79.12,219.82L45.07,231.17a16,16,0,0,1-20.24-20.24l11.35-34.05A104,104,0,1,1,232,128Zm-16,0A88,88,0,1,0,51.81,172.06a8,8,0,0,1,.66,6.54L40,216,77.4,203.53a7.85,7.85,0,0,1,2.53-.42,8,8,0,0,1,4,1.08A88,88,0,0,0,216,128Z")
    }

    /** Phosphor `chats-circle-fill`. */
    val ChatsCircleFill: ImageVector by lazy {
        icon("ChatsCircleFill", 256f, false,
        "M232.07,186.76a80,80,0,0,0-62.5-114.17A80,80,0,1,0,23.93,138.76l-7.27,24.71a16,16,0,0,0,19.87,19.87l24.71-7.27a80.39,80.39,0,0,0,25.18,7.35,80,80,0,0,0,108.34,40.65l24.71,7.27a16,16,0,0,0,19.87-19.86Zm-16.25,1.47L224,216l-27.76-8.17a8,8,0,0,0-6,.63,64.05,64.05,0,0,1-85.87-24.88A79.93,79.93,0,0,0,174.7,89.71a64,64,0,0,1,41.75,92.48A8,8,0,0,0,215.82,188.23Z")
    }

    /** Phosphor `chats-teardrop-fill`. */
    val ChatsTeardropFill: ImageVector by lazy {
        icon("ChatsTeardropFill", 256f, false,
        "M169.57,72.59A80,80,0,0,0,16,104v64a16,16,0,0,0,16,16H86.67A80.15,80.15,0,0,0,160,232h64a16,16,0,0,0,16-16V152A80,80,0,0,0,169.57,72.59ZM224,216H160a64.14,64.14,0,0,1-55.68-32.43A79.93,79.93,0,0,0,174.7,89.71,64,64,0,0,1,224,152Z")
    }

    /** Phosphor `check-bold`. */
    val CheckBold: ImageVector by lazy {
        icon("CheckBold", 256f, false,
        "M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z")
    }

    /** Phosphor `check-circle-fill`. */
    val CheckCircleFill: ImageVector by lazy {
        icon("CheckCircleFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm45.66,85.66-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35a8,8,0,0,1,11.32,11.32Z")
    }

    /** Phosphor `check`. */
    val CheckRegular: ImageVector by lazy {
        icon("CheckRegular", 256f, false,
        "M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z")
    }

    /** Phosphor `circle-half-fill`. */
    val CircleHalfFill: ImageVector by lazy {
        icon("CircleHalfFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM40,128a88.1,88.1,0,0,1,88-88V216A88.1,88.1,0,0,1,40,128Z")
    }

    /** Phosphor `circle`. */
    val CircleRegular: ImageVector by lazy {
        icon("CircleRegular", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Z")
    }

    /** Phosphor `copy`. */
    val CopyRegular: ImageVector by lazy {
        icon("CopyRegular", 256f, false,
        "M216,32H88a8,8,0,0,0-8,8V80H40a8,8,0,0,0-8,8V216a8,8,0,0,0,8,8H168a8,8,0,0,0,8-8V176h40a8,8,0,0,0,8-8V40A8,8,0,0,0,216,32ZM160,208H48V96H160Zm48-48H176V88a8,8,0,0,0-8-8H96V48H208Z")
    }

    /** Phosphor `crop`. */
    val Crop: ImageVector by lazy {
        icon("Crop", 256f, false,
        "M240,192a8,8,0,0,1-8,8H200v32a8,8,0,0,1-16,0V200H64a8,8,0,0,1-8-8V72H24a8,8,0,0,1,0-16H56V24a8,8,0,0,1,16,0V184H232A8,8,0,0,1,240,192ZM96,72h88v88a8,8,0,0,0,16,0V64a8,8,0,0,0-8-8H96a8,8,0,0,0,0,16Z")
    }

    /** Phosphor `desktop-fill`. */
    val DesktopFill: ImageVector by lazy {
        icon("DesktopFill", 256f, false,
        "M208,40H48A24,24,0,0,0,24,64V176a24,24,0,0,0,24,24h72v16H96a8,8,0,0,0,0,16h64a8,8,0,0,0,0-16H136V200h72a24,24,0,0,0,24-24V64A24,24,0,0,0,208,40Zm0,144H48a8,8,0,0,1-8-8V160H216v16A8,8,0,0,1,208,184Z")
    }

    /** Phosphor `device-mobile-fill`. */
    val DeviceMobileFill: ImageVector by lazy {
        icon("DeviceMobileFill", 256f, false,
        "M176,16H80A24,24,0,0,0,56,40V216a24,24,0,0,0,24,24h96a24,24,0,0,0,24-24V40A24,24,0,0,0,176,16ZM80,32h96a8,8,0,0,1,8,8v8H72V40A8,8,0,0,1,80,32Zm96,192H80a8,8,0,0,1-8-8v-8H184v8A8,8,0,0,1,176,224Z")
    }

    /** Phosphor `device-tablet-fill`. */
    val DeviceTabletFill: ImageVector by lazy {
        icon("DeviceTabletFill", 256f, false,
        "M192,24H64A24,24,0,0,0,40,48V208a24,24,0,0,0,24,24H192a24,24,0,0,0,24-24V48A24,24,0,0,0,192,24ZM64,40H192a8,8,0,0,1,8,8v8H56V48A8,8,0,0,1,64,40ZM192,216H64a8,8,0,0,1-8-8v-8H200v8A8,8,0,0,1,192,216Z")
    }

    /** Phosphor `dots-three-bold`. */
    val DotsThreeBold: ImageVector by lazy {
        icon("DotsThreeBold", 256f, false,
        "M144,128a16,16,0,1,1-16-16A16,16,0,0,1,144,128ZM60,112a16,16,0,1,0,16,16A16,16,0,0,0,60,112Zm136,0a16,16,0,1,0,16,16A16,16,0,0,0,196,112Z")
    }

    /** Phosphor `download-simple`. */
    val DownloadSimple: ImageVector by lazy {
        icon("DownloadSimple", 256f, false,
        "M224,144v64a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V144a8,8,0,0,1,16,0v56H208V144a8,8,0,0,1,16,0Zm-101.66,5.66a8,8,0,0,0,11.32,0l40-40a8,8,0,0,0-11.32-11.32L136,124.69V32a8,8,0,0,0-16,0v92.69L93.66,98.34a8,8,0,0,0-11.32,11.32Z")
    }

    /** Phosphor `export-bold`. */
    val ExportBold: ImageVector by lazy {
        icon("ExportBold", 256f, false,
        "M220,112v96a20,20,0,0,1-20,20H56a20,20,0,0,1-20-20V112A20,20,0,0,1,56,92H76a12,12,0,0,1,0,24H60v88H196V116H180a12,12,0,0,1,0-24h20A20,20,0,0,1,220,112ZM96.49,72.49,116,53v83a12,12,0,0,0,24,0V53l19.51,19.52a12,12,0,1,0,17-17l-40-40a12,12,0,0,0-17,0l-40,40a12,12,0,1,0,17,17Z")
    }

    /** Phosphor `file-fill`. */
    val FileFill: ImageVector by lazy {
        icon("FileFill", 256f, false,
        "M213.66,82.34l-56-56A8,8,0,0,0,152,24H56A16,16,0,0,0,40,40V216a16,16,0,0,0,16,16H200a16,16,0,0,0,16-16V88A8,8,0,0,0,213.66,82.34ZM152,88V44l44,44Z")
    }

    /** Phosphor `fingerprint`. */
    val Fingerprint: ImageVector by lazy {
        icon("Fingerprint", 256f, false,
        "M72,128a134.63,134.63,0,0,1-14.16,60.47,8,8,0,1,1-14.32-7.12A118.8,118.8,0,0,0,56,128,71.73,71.73,0,0,1,83,71.8,8,8,0,1,1,93,84.29,55.76,55.76,0,0,0,72,128Zm56-8a8,8,0,0,0-8,8,184.12,184.12,0,0,1-23,89.1,8,8,0,0,0,14,7.76A200.19,200.19,0,0,0,136,128,8,8,0,0,0,128,120Zm0-32a40,40,0,0,0-40,40,8,8,0,0,0,16,0,24,24,0,0,1,48,0,214.09,214.09,0,0,1-20.51,92A8,8,0,1,0,146,226.83,230,230,0,0,0,168,128,40,40,0,0,0,128,88Zm0-64A104.11,104.11,0,0,0,24,128a87.76,87.76,0,0,1-5,29.33,8,8,0,0,0,15.09,5.33A103.9,103.9,0,0,0,40,128a88,88,0,0,1,176,0,282.24,282.24,0,0,1-5.29,54.45,8,8,0,0,0,6.3,9.4,8.22,8.22,0,0,0,1.55.15,8,8,0,0,0,7.84-6.45A298.37,298.37,0,0,0,232,128,104.12,104.12,0,0,0,128,24ZM94.4,152.17A8,8,0,0,0,85,158.42a151,151,0,0,1-17.21,45.44,8,8,0,0,0,13.86,8,166.67,166.67,0,0,0,19-50.25A8,8,0,0,0,94.4,152.17ZM128,56a72.85,72.85,0,0,0-9,.56,8,8,0,0,0,2,15.87A56.08,56.08,0,0,1,184,128a252.12,252.12,0,0,1-1.92,31A8,8,0,0,0,189,168a8.39,8.39,0,0,0,1,.06,8,8,0,0,0,7.92-7,266.48,266.48,0,0,0,2-33A72.08,72.08,0,0,0,128,56Zm57.93,128.25a8,8,0,0,0-9.75,5.75c-1.46,5.69-3.15,11.4-5,17a8,8,0,0,0,5,10.13,7.88,7.88,0,0,0,2.55.42,8,8,0,0,0,7.58-5.46c2-5.92,3.79-12,5.35-18.05A8,8,0,0,0,185.94,184.26Z")
    }

    /** Phosphor `folder-simple-fill`. */
    val FolderSimpleFill: ImageVector by lazy {
        icon("FolderSimpleFill", 256f, false,
        "M232,88V200.89A15.13,15.13,0,0,1,216.89,216H40a16,16,0,0,1-16-16V64A16,16,0,0,1,40,48H93.33a16.12,16.12,0,0,1,9.6,3.2L130.67,72H216A16,16,0,0,1,232,88Z")
    }

    /** Phosphor `gear-six-fill`. */
    val GearSixFill: ImageVector by lazy {
        icon("GearSixFill", 256f, false,
        "M237.94,107.21a8,8,0,0,0-3.89-5.4l-29.83-17-.12-33.62a8,8,0,0,0-2.83-6.08,111.91,111.91,0,0,0-36.72-20.67,8,8,0,0,0-6.46.59L128,41.85,97.88,25a8,8,0,0,0-6.47-.6A111.92,111.92,0,0,0,54.73,45.15a8,8,0,0,0-2.83,6.07l-.15,33.65-29.83,17a8,8,0,0,0-3.89,5.4,106.47,106.47,0,0,0,0,41.56,8,8,0,0,0,3.89,5.4l29.83,17,.12,33.63a8,8,0,0,0,2.83,6.08,111.91,111.91,0,0,0,36.72,20.67,8,8,0,0,0,6.46-.59L128,214.15,158.12,231a7.91,7.91,0,0,0,3.9,1,8.09,8.09,0,0,0,2.57-.42,112.1,112.1,0,0,0,36.68-20.73,8,8,0,0,0,2.83-6.07l.15-33.65,29.83-17a8,8,0,0,0,3.89-5.4A106.47,106.47,0,0,0,237.94,107.21ZM128,168a40,40,0,1,1,40-40A40,40,0,0,1,128,168Z")
    }

    /** Phosphor `gift-fill`. */
    val GiftFill: ImageVector by lazy {
        icon("GiftFill", 256f, false,
        "M216,72H180.92c.39-.33.79-.65,1.17-1A29.53,29.53,0,0,0,192,49.57,32.62,32.62,0,0,0,158.44,16,29.53,29.53,0,0,0,137,25.91a54.94,54.94,0,0,0-9,14.48,54.94,54.94,0,0,0-9-14.48A29.53,29.53,0,0,0,97.56,16,32.62,32.62,0,0,0,64,49.57,29.53,29.53,0,0,0,73.91,71c.38.33.78.65,1.17,1H40A16,16,0,0,0,24,88v32a16,16,0,0,0,16,16v64a16,16,0,0,0,16,16h60a4,4,0,0,0,4-4V120H40V88h80v32h16V88h80v32H136v92a4,4,0,0,0,4,4h60a16,16,0,0,0,16-16V136a16,16,0,0,0,16-16V88A16,16,0,0,0,216,72ZM84.51,59a13.69,13.69,0,0,1-4.5-10A16.62,16.62,0,0,1,96.59,32h.49a13.69,13.69,0,0,1,10,4.5c8.39,9.48,11.35,25.2,12.39,34.92C109.71,70.39,94,67.43,84.51,59Zm87,0c-9.49,8.4-25.24,11.36-35,12.4C137.7,60.89,141,45.5,149,36.51a13.69,13.69,0,0,1,10-4.5h.49A16.62,16.62,0,0,1,176,49.08,13.69,13.69,0,0,1,171.49,59Z")
    }

    /** Phosphor `globe`. */
    val GlobeRegular: ImageVector by lazy {
        icon("GlobeRegular", 256f, false,
        "M128,24h0A104,104,0,1,0,232,128,104.12,104.12,0,0,0,128,24Zm88,104a87.61,87.61,0,0,1-3.33,24H174.16a157.44,157.44,0,0,0,0-48h38.51A87.61,87.61,0,0,1,216,128ZM102,168H154a115.11,115.11,0,0,1-26,45A115.27,115.27,0,0,1,102,168Zm-3.9-16a140.84,140.84,0,0,1,0-48h59.88a140.84,140.84,0,0,1,0,48ZM40,128a87.61,87.61,0,0,1,3.33-24H81.84a157.44,157.44,0,0,0,0,48H43.33A87.61,87.61,0,0,1,40,128ZM154,88H102a115.11,115.11,0,0,1,26-45A115.27,115.27,0,0,1,154,88Zm52.33,0H170.71a135.28,135.28,0,0,0-22.3-45.6A88.29,88.29,0,0,1,206.37,88ZM107.59,42.4A135.28,135.28,0,0,0,85.29,88H49.63A88.29,88.29,0,0,1,107.59,42.4ZM49.63,168H85.29a135.28,135.28,0,0,0,22.3,45.6A88.29,88.29,0,0,1,49.63,168Zm98.78,45.6a135.28,135.28,0,0,0,22.3-45.6h35.66A88.29,88.29,0,0,1,148.41,213.6Z")
    }

    /** Phosphor `hard-drive-fill`. */
    val HardDriveFill: ImageVector by lazy {
        icon("HardDriveFill", 256f, false,
        "M224,64H32A16,16,0,0,0,16,80v96a16,16,0,0,0,16,16H224a16,16,0,0,0,16-16V80A16,16,0,0,0,224,64Zm-36,76a12,12,0,1,1,12-12A12,12,0,0,1,188,140Z")
    }

    /** Phosphor `hard-drives-fill`. */
    val HardDrivesFill: ImageVector by lazy {
        icon("HardDrivesFill", 256f, false,
        "M208,40H48A16,16,0,0,0,32,56v48a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V56A16,16,0,0,0,208,40ZM180,92a12,12,0,1,1,12-12A12,12,0,0,1,180,92Z",
        "M208,136H48a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V152A16,16,0,0,0,208,136Zm-28,52a12,12,0,1,1,12-12A12,12,0,0,1,180,188Z")
    }

    /** Phosphor `heart-fill`. */
    val HeartFill: ImageVector by lazy {
        icon("HeartFill", 256f, false,
        "M240,102c0,70-103.79,126.66-108.21,129a8,8,0,0,1-7.58,0C119.79,228.66,16,172,16,102A62.07,62.07,0,0,1,78,40c20.65,0,38.73,8.88,50,23.89C139.27,48.88,157.35,40,178,40A62.07,62.07,0,0,1,240,102Z")
    }

    /** Phosphor `identification-card-bold`. */
    val IdentificationCardBold: ImageVector by lazy {
        icon("IdentificationCardBold", 256f, false,
        "M148,108a12,12,0,0,1,12-12h28a12,12,0,0,1,0,24H160A12,12,0,0,1,148,108Zm40,28H168a12,12,0,0,0,0,24h20a12,12,0,0,0,0-24Zm48-80V200a20,20,0,0,1-20,20H40a20,20,0,0,1-20-20V56A20,20,0,0,1,40,36H216A20,20,0,0,1,236,56Zm-24,4H44V196H212ZM58.28,159.37A43.82,43.82,0,0,1,71.53,142a36,36,0,1,1,56.94,0,43.84,43.84,0,0,1,13.26,17.37,12,12,0,0,1-22.15,9.26C116.48,161.19,108.42,156,100,156s-16.47,5.2-19.59,12.63a12,12,0,1,1-22.13-9.26ZM88,120a12,12,0,1,0,12-12A12,12,0,0,0,88,120Z")
    }

    /** Phosphor `image-fill`. */
    val ImageFill: ImageVector by lazy {
        icon("ImageFill", 256f, false,
        "M216,40H40A16,16,0,0,0,24,56V200a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A16,16,0,0,0,216,40ZM156,88a12,12,0,1,1-12,12A12,12,0,0,1,156,88Zm60,112H40V160.69l46.34-46.35a8,8,0,0,1,11.32,0h0L165,181.66a8,8,0,0,0,11.32-11.32l-17.66-17.65L173,138.34a8,8,0,0,1,11.31,0L216,170.07V200Z")
    }

    /** Phosphor `image`. */
    val ImageRegular: ImageVector by lazy {
        icon("ImageRegular", 256f, false,
        "M216,40H40A16,16,0,0,0,24,56V200a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V56A16,16,0,0,0,216,40Zm0,16V158.75l-26.07-26.06a16,16,0,0,0-22.63,0l-20,20-44-44a16,16,0,0,0-22.62,0L40,149.37V56ZM40,172l52-52,80,80H40Zm176,28H194.63l-36-36,20-20L216,181.38V200ZM144,100a12,12,0,1,1,12,12A12,12,0,0,1,144,100Z")
    }

    /** Phosphor `info-fill`. */
    val InfoFill: ImageVector by lazy {
        icon("InfoFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm-4,48a12,12,0,1,1-12,12A12,12,0,0,1,124,72Zm12,112a16,16,0,0,1-16-16V128a8,8,0,0,1,0-16,16,16,0,0,1,16,16v40a8,8,0,0,1,0,16Z")
    }

    /** Phosphor `key-fill`. */
    val KeyFill: ImageVector by lazy {
        icon("KeyFill", 256f, false,
        "M216.57,39.43A80,80,0,0,0,83.91,120.78L28.69,176A15.86,15.86,0,0,0,24,187.31V216a16,16,0,0,0,16,16H72a8,8,0,0,0,8-8V208H96a8,8,0,0,0,8-8V184h16a8,8,0,0,0,5.66-2.34l9.56-9.57A79.73,79.73,0,0,0,160,176h.1A80,80,0,0,0,216.57,39.43ZM180,92a16,16,0,1,1,16-16A16,16,0,0,1,180,92Z")
    }

    /** Phosphor `laptop-fill`. */
    val LaptopFill: ImageVector by lazy {
        icon("LaptopFill", 256f, false,
        "M232,168h-8V72a24,24,0,0,0-24-24H56A24,24,0,0,0,32,72v96H24a8,8,0,0,0-8,8v16a24,24,0,0,0,24,24H216a24,24,0,0,0,24-24V176A8,8,0,0,0,232,168ZM112,72h32a8,8,0,0,1,0,16H112a8,8,0,0,1,0-16ZM224,192a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8v-8H224Z")
    }

    /** Phosphor `list-checks`. */
    val ListChecks: ImageVector by lazy {
        icon("ListChecks", 256f, false,
        "M224,128a8,8,0,0,1-8,8H128a8,8,0,0,1,0-16h88A8,8,0,0,1,224,128ZM128,72h88a8,8,0,0,0,0-16H128a8,8,0,0,0,0,16Zm88,112H128a8,8,0,0,0,0,16h88a8,8,0,0,0,0-16ZM82.34,42.34,56,68.69,45.66,58.34A8,8,0,0,0,34.34,69.66l16,16a8,8,0,0,0,11.32,0l32-32A8,8,0,0,0,82.34,42.34Zm0,64L56,132.69,45.66,122.34a8,8,0,0,0-11.32,11.32l16,16a8,8,0,0,0,11.32,0l32-32a8,8,0,0,0-11.32-11.32Zm0,64L56,196.69,45.66,186.34a8,8,0,0,0-11.32,11.32l16,16a8,8,0,0,0,11.32,0l32-32a8,8,0,0,0-11.32-11.32Z")
    }

    /** Phosphor `lock-fill`. */
    val LockFill: ImageVector by lazy {
        icon("LockFill", 256f, false,
        "M208,80H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80Zm-80,84a12,12,0,1,1,12-12A12,12,0,0,1,128,164Zm32-84H96V56a32,32,0,0,1,64,0Z")
    }

    /** Phosphor `lock-simple-fill`. */
    val LockSimpleFill: ImageVector by lazy {
        icon("LockSimpleFill", 256f, false,
        "M208,80H176V56a48,48,0,0,0-96,0V80H48A16,16,0,0,0,32,96V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V96A16,16,0,0,0,208,80ZM96,56a32,32,0,0,1,64,0V80H96Z")
    }

    /** Phosphor `lock-simple-open-fill`. */
    val LockSimpleOpenFill: ImageVector by lazy {
        icon("LockSimpleOpenFill", 256f, false,
        "M224,96V208a16,16,0,0,1-16,16H48a16,16,0,0,1-16-16V96A16,16,0,0,1,48,80H80V56A48.05,48.05,0,0,1,128,8c23.2,0,43.32,16.15,47.84,38.41a8,8,0,0,1-15.68,3.18C157.2,35,143.37,24,128,24A32,32,0,0,0,96,56V80H208A16,16,0,0,1,224,96Z")
    }

    /** Phosphor `magic-wand`. */
    val MagicWand: ImageVector by lazy {
        icon("MagicWand", 256f, false,
        "M48,64a8,8,0,0,1,8-8H72V40a8,8,0,0,1,16,0V56h16a8,8,0,0,1,0,16H88V88a8,8,0,0,1-16,0V72H56A8,8,0,0,1,48,64ZM184,192h-8v-8a8,8,0,0,0-16,0v8h-8a8,8,0,0,0,0,16h8v8a8,8,0,0,0,16,0v-8h8a8,8,0,0,0,0-16Zm56-48H224V128a8,8,0,0,0-16,0v16H192a8,8,0,0,0,0,16h16v16a8,8,0,0,0,16,0V160h16a8,8,0,0,0,0-16ZM219.31,80,80,219.31a16,16,0,0,1-22.62,0L36.68,198.63a16,16,0,0,1,0-22.63L176,36.69a16,16,0,0,1,22.63,0l20.68,20.68A16,16,0,0,1,219.31,80Zm-54.63,32L144,91.31l-96,96L68.68,208ZM208,68.69,187.31,48l-32,32L176,100.69Z")
    }

    /** Phosphor `magnifying-glass`. */
    val MagnifyingGlass: ImageVector by lazy {
        icon("MagnifyingGlass", 256f, false,
        "M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z")
    }

    /** Phosphor `magnifying-glass-bold`. */
    val MagnifyingGlassBold: ImageVector by lazy {
        icon("MagnifyingGlassBold", 256f, false,
        "M232.49,215.51,185,168a92.12,92.12,0,1,0-17,17l47.53,47.54a12,12,0,0,0,17-17ZM44,112a68,68,0,1,1,68,68A68.07,68.07,0,0,1,44,112Z")
    }

    /** Phosphor `map-pin-fill`. */
    val MapPinFill: ImageVector by lazy {
        icon("MapPinFill", 256f, false,
        "M128,16a88.1,88.1,0,0,0-88,88c0,75.3,80,132.17,83.41,134.55a8,8,0,0,0,9.18,0C136,236.17,216,179.3,216,104A88.1,88.1,0,0,0,128,16Zm0,56a32,32,0,1,1-32,32A32,32,0,0,1,128,72Z")
    }

    /** Phosphor `microphone-fill`. */
    val MicrophoneFill: ImageVector by lazy {
        icon("MicrophoneFill", 256f, false,
        "M80,128V64a48,48,0,0,1,96,0v64a48,48,0,0,1-96,0Zm128,0a8,8,0,0,0-16,0,64,64,0,0,1-128,0,8,8,0,0,0-16,0,80.11,80.11,0,0,0,72,79.6V240a8,8,0,0,0,16,0V207.6A80.11,80.11,0,0,0,208,128Z")
    }

    /** Phosphor `microphone-slash-fill`. */
    val MicrophoneSlashFill: ImageVector by lazy {
        icon("MicrophoneSlashFill", 256f, false,
        "M213.38,229.92a8,8,0,0,1-11.3-.54l-30.92-34A78.83,78.83,0,0,1,136,207.59V240a8,8,0,0,1-16,0V207.6A80.11,80.11,0,0,1,48,128a8,8,0,0,1,16,0,64.07,64.07,0,0,0,64,64,63.41,63.41,0,0,0,32.21-8.68l-11.1-12.2A48,48,0,0,1,80,128V95.09L42.08,53.38A8,8,0,0,1,53.92,42.62l160,176A8,8,0,0,1,213.38,229.92Zm-24.19-63.13a7.88,7.88,0,0,0,3.51.82,8,8,0,0,0,7.19-4.49A79.16,79.16,0,0,0,208,128a8,8,0,0,0-16,0,63.32,63.32,0,0,1-6.48,28.09A8,8,0,0,0,189.19,166.79Zm-27.33-29.22A8,8,0,0,0,175.74,133a49.49,49.49,0,0,0,.26-5V64A48,48,0,0,0,84,44.87a8,8,0,0,0,1.41,8.57Z")
    }

    /** Phosphor `moon-fill`. */
    val MoonFill: ImageVector by lazy {
        icon("MoonFill", 256f, false,
        "M235.54,150.21a104.84,104.84,0,0,1-37,52.91A104,104,0,0,1,32,120,103.09,103.09,0,0,1,52.88,57.48a104.84,104.84,0,0,1,52.91-37,8,8,0,0,1,10,10,88.08,88.08,0,0,0,109.8,109.8,8,8,0,0,1,10,10Z")
    }

    /** Phosphor `music-note-fill`. */
    val MusicNoteFill: ImageVector by lazy {
        icon("MusicNoteFill", 256f, false,
        "M210.3,56.34l-80-24A8,8,0,0,0,120,40V148.26A48,48,0,1,0,136,184V98.75l69.7,20.91A8,8,0,0,0,216,112V64A8,8,0,0,0,210.3,56.34Z")
    }

    /** Phosphor `palette-fill`. */
    val PaletteFill: ImageVector by lazy {
        icon("PaletteFill", 256f, false,
        "M200.77,53.89A103.27,103.27,0,0,0,128,24h-1.07A104,104,0,0,0,24,128c0,43,26.58,79.06,69.36,94.17A32,32,0,0,0,136,192a16,16,0,0,1,16-16h46.21a31.81,31.81,0,0,0,31.2-24.88,104.43,104.43,0,0,0,2.59-24A103.28,103.28,0,0,0,200.77,53.89ZM84,168a12,12,0,1,1,12-12A12,12,0,0,1,84,168Zm0-56a12,12,0,1,1,12-12A12,12,0,0,1,84,112Zm44-24a12,12,0,1,1,12-12A12,12,0,0,1,128,88Zm44,24a12,12,0,1,1,12-12A12,12,0,0,1,172,112Z")
    }

    /** Phosphor `paper-plane-tilt-fill`. */
    val PaperPlaneTiltFill: ImageVector by lazy {
        icon("PaperPlaneTiltFill", 256f, false,
        "M231.4,44.34s0,.1,0,.15l-58.2,191.94a15.88,15.88,0,0,1-14,11.51q-.69.06-1.38.06a15.86,15.86,0,0,1-14.42-9.15L107,164.15a4,4,0,0,1,.77-4.58l57.92-57.92a8,8,0,0,0-11.31-11.31L96.43,148.26a4,4,0,0,1-4.58.77L17.08,112.64a16,16,0,0,1,2.49-29.8l191.94-58.2.15,0A16,16,0,0,1,231.4,44.34Z")
    }

    /** Phosphor `pause-fill`. */
    val PauseFill: ImageVector by lazy {
        icon("PauseFill", 256f, false,
        "M216,48V208a16,16,0,0,1-16,16H160a16,16,0,0,1-16-16V48a16,16,0,0,1,16-16h40A16,16,0,0,1,216,48ZM96,32H56A16,16,0,0,0,40,48V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V48A16,16,0,0,0,96,32Z")
    }

    /** Phosphor `pen-nib`. */
    val PenNib: ImageVector by lazy {
        icon("PenNib", 256f, false,
        "M248,92.68a15.86,15.86,0,0,0-4.69-11.31L174.63,12.68a16,16,0,0,0-22.63,0L123.57,41.11l-58,21.77A16.06,16.06,0,0,0,55.35,75.23L32.11,214.68A8,8,0,0,0,40,224a8.4,8.4,0,0,0,1.32-.11l139.44-23.24a16,16,0,0,0,12.35-10.17l21.77-58L243.31,104A15.87,15.87,0,0,0,248,92.68Zm-69.87,92.19L63.32,204l47.37-47.37a28,28,0,1,0-11.32-11.32L52,192.7,71.13,77.86,126,57.29,198.7,130ZM112,132a12,12,0,1,1,12,12A12,12,0,0,1,112,132Zm96-15.32L139.31,48l24-24L232,92.68Z")
    }

    /** Phosphor `pencil-circle`. */
    val PencilCircle: ImageVector by lazy {
        icon("PencilCircle", 256f, false,
        "M201.54,54.46A104,104,0,0,0,54.46,201.54,104,104,0,0,0,201.54,54.46ZM88,192a16,16,0,0,1,32,0v23.59a88,88,0,0,1-32-9.22Zm48,0a16,16,0,0,1,32,0v14.37a88,88,0,0,1-32,9.22Zm-28.73-56h41.46l11.58,25.1A31.93,31.93,0,0,0,128,170.87a31.93,31.93,0,0,0-32.31-9.77Zm7.39-16L128,91.09,141.34,120Zm75.56,70.23c-2,2-4.08,3.87-6.22,5.64V176a7.91,7.91,0,0,0-.74-3.35l-48-104a8,8,0,0,0-14.52,0l-48,104A7.91,7.91,0,0,0,72,176v19.87c-2.14-1.77-4.22-3.64-6.22-5.64a88,88,0,1,1,124.44,0Z")
    }

    /** Phosphor `phone-disconnect-fill`. */
    val PhoneDisconnectFill: ImageVector by lazy {
        icon("PhoneDisconnectFill", 256f, false,
        "M236.28,161.84a16,16,0,0,1-18.38,5.06l-49-17.39-.29-.11a16,16,0,0,1-9.72-11.59l-6.21-29.75h0a76.52,76.52,0,0,0-49.68.11l-5.9,29.52a16,16,0,0,1-9.75,11.73l-.29.11-49,17.37A15.8,15.8,0,0,1,32.35,168a16,16,0,0,1-12.63-6.14c-17.23-22.22-15.3-51.71,4.69-71.71,56.15-56.17,151-56.17,207.18,0h0C251.58,110.13,253.51,139.62,236.28,161.84ZM216,192H40a8,8,0,0,0,0,16H216a8,8,0,0,0,0-16Z")
    }

    /** Phosphor `phone-fill`. */
    val PhoneFill: ImageVector by lazy {
        icon("PhoneFill", 256f, false,
        "M231.88,175.08A56.26,56.26,0,0,1,176,224C96.6,224,32,159.4,32,80A56.26,56.26,0,0,1,80.92,24.12a16,16,0,0,1,16.62,9.52l21.12,47.15,0,.12A16,16,0,0,1,117.39,96c-.18.27-.37.52-.57.77L96,121.45c7.49,15.22,23.41,31,38.83,38.51l24.34-20.71a8.12,8.12,0,0,1,.75-.56,16,16,0,0,1,15.17-1.4l.13.06,47.11,21.11A16,16,0,0,1,231.88,175.08Z")
    }

    /** Phosphor `play-fill`. */
    val PlayFill: ImageVector by lazy {
        icon("PlayFill", 256f, false,
        "M240,128a15.74,15.74,0,0,1-7.6,13.51L88.32,229.65a16,16,0,0,1-16.2.3A15.86,15.86,0,0,1,64,216.13V39.87a15.86,15.86,0,0,1,8.12-13.82,16,16,0,0,1,16.2.3L232.4,114.49A15.74,15.74,0,0,1,240,128Z")
    }

    /** Phosphor `plus-bold`. */
    val PlusBold: ImageVector by lazy {
        icon("PlusBold", 256f, false,
        "M228,128a12,12,0,0,1-12,12H140v76a12,12,0,0,1-24,0V140H40a12,12,0,0,1,0-24h76V40a12,12,0,0,1,24,0v76h76A12,12,0,0,1,228,128Z")
    }

    /** Phosphor `qr-code`. */
    val QrCodeRegular: ImageVector by lazy {
        icon("QrCodeRegular", 256f, false,
        "M104,40H56A16,16,0,0,0,40,56v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V56A16,16,0,0,0,104,40Zm0,64H56V56h48v48Zm0,32H56a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V152A16,16,0,0,0,104,136Zm0,64H56V152h48v48ZM200,40H152a16,16,0,0,0-16,16v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V56A16,16,0,0,0,200,40Zm0,64H152V56h48v48Zm-64,72V144a8,8,0,0,1,16,0v32a8,8,0,0,1-16,0Zm80-16a8,8,0,0,1-8,8H184v40a8,8,0,0,1-8,8H144a8,8,0,0,1,0-16h24V144a8,8,0,0,1,16,0v8h24A8,8,0,0,1,216,160Zm0,32v16a8,8,0,0,1-16,0V192a8,8,0,0,1,16,0Z")
    }

    /** Phosphor `seal-check-fill`. */
    val SealCheckFill: ImageVector by lazy {
        icon("SealCheckFill", 256f, false,
        "M225.86,102.82c-3.77-3.94-7.67-8-9.14-11.57-1.36-3.27-1.44-8.69-1.52-13.94-.15-9.76-.31-20.82-8-28.51s-18.75-7.85-28.51-8c-5.25-.08-10.67-.16-13.94-1.52-3.56-1.47-7.63-5.37-11.57-9.14C146.28,23.51,138.44,16,128,16s-18.27,7.51-25.18,14.14c-3.94,3.77-8,7.67-11.57,9.14C88,40.64,82.56,40.72,77.31,40.8c-9.76.15-20.82.31-28.51,8S41,67.55,40.8,77.31c-.08,5.25-.16,10.67-1.52,13.94-1.47,3.56-5.37,7.63-9.14,11.57C23.51,109.72,16,117.56,16,128s7.51,18.27,14.14,25.18c3.77,3.94,7.67,8,9.14,11.57,1.36,3.27,1.44,8.69,1.52,13.94.15,9.76.31,20.82,8,28.51s18.75,7.85,28.51,8c5.25.08,10.67.16,13.94,1.52,3.56,1.47,7.63,5.37,11.57,9.14C109.72,232.49,117.56,240,128,240s18.27-7.51,25.18-14.14c3.94-3.77,8-7.67,11.57-9.14,3.27-1.36,8.69-1.44,13.94-1.52,9.76-.15,20.82-.31,28.51-8s7.85-18.75,8-28.51c.08-5.25.16-10.67,1.52-13.94,1.47-3.56,5.37-7.63,9.14-11.57C232.49,146.28,240,138.44,240,128S232.49,109.73,225.86,102.82Zm-52.2,6.84-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35a8,8,0,0,1,11.32,11.32Z")
    }

    /** Phosphor `shield-check-fill`. */
    val ShieldCheckFill: ImageVector by lazy {
        icon("ShieldCheckFill", 256f, false,
        "M208,40H48A16,16,0,0,0,32,56v56c0,52.72,25.52,84.67,46.93,102.19,23.06,18.86,46,25.26,47,25.53a8,8,0,0,0,4.2,0c1-.27,23.91-6.67,47-25.53C198.48,196.67,224,164.72,224,112V56A16,16,0,0,0,208,40Zm-34.32,69.66-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35a8,8,0,0,1,11.32,11.32Z")
    }

    /** Phosphor `shield-warning-fill`. */
    val ShieldWarningFill: ImageVector by lazy {
        icon("ShieldWarningFill", 256f, false,
        "M208,40H48A16,16,0,0,0,32,56v56c0,52.72,25.52,84.67,46.93,102.19,23.06,18.86,46,25.27,47,25.53a8,8,0,0,0,4.2,0c1-.26,23.91-6.67,47-25.53C198.48,196.67,224,164.72,224,112V56A16,16,0,0,0,208,40ZM120,96a8,8,0,0,1,16,0v40a8,8,0,0,1-16,0Zm8,88a12,12,0,1,1,12-12A12,12,0,0,1,128,184Z")
    }

    /** Phosphor `sliders-horizontal`. */
    val SlidersHorizontal: ImageVector by lazy {
        icon("SlidersHorizontal", 256f, false,
        "M40,88H73a32,32,0,0,0,62,0h81a8,8,0,0,0,0-16H135a32,32,0,0,0-62,0H40a8,8,0,0,0,0,16Zm64-24A16,16,0,1,1,88,80,16,16,0,0,1,104,64ZM216,168H199a32,32,0,0,0-62,0H40a8,8,0,0,0,0,16h97a32,32,0,0,0,62,0h17a8,8,0,0,0,0-16Zm-48,24a16,16,0,1,1,16-16A16,16,0,0,1,168,192Z")
    }

    /** Phosphor `smiley`. */
    val Smiley: ImageVector by lazy {
        icon("Smiley", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216ZM80,108a12,12,0,1,1,12,12A12,12,0,0,1,80,108Zm96,0a12,12,0,1,1-12-12A12,12,0,0,1,176,108Zm-1.07,48c-10.29,17.79-27.4,28-46.93,28s-36.63-10.2-46.92-28a8,8,0,1,1,13.84-8c7.47,12.91,19.21,20,33.08,20s25.61-7.1,33.07-20a8,8,0,0,1,13.86,8Z")
    }

    /** Phosphor `smiley-fill`. */
    val SmileyFill: ImageVector by lazy {
        icon("SmileyFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM92,96a12,12,0,1,1-12,12A12,12,0,0,1,92,96Zm82.92,60c-10.29,17.79-27.39,28-46.92,28s-36.63-10.2-46.92-28a8,8,0,1,1,13.84-8c7.47,12.91,19.21,20,33.08,20s25.61-7.1,33.08-20a8,8,0,1,1,13.84,8ZM164,120a12,12,0,1,1,12-12A12,12,0,0,1,164,120Z")
    }

    /** Phosphor `speaker-high-fill`. */
    val SpeakerHighFill: ImageVector by lazy {
        icon("SpeakerHighFill", 256f, false,
        "M160,32.25V223.69a8.29,8.29,0,0,1-3.91,7.18,8,8,0,0,1-9-.56l-65.57-51A4,4,0,0,1,80,176.16V79.84a4,4,0,0,1,1.55-3.15l65.57-51a8,8,0,0,1,10,.16A8.27,8.27,0,0,1,160,32.25ZM60,80H32A16,16,0,0,0,16,96v64a16,16,0,0,0,16,16H60a4,4,0,0,0,4-4V84A4,4,0,0,0,60,80Zm126.77,20.84a8,8,0,0,0-.72,11.3,24,24,0,0,1,0,31.72,8,8,0,1,0,12,10.58,40,40,0,0,0,0-52.88A8,8,0,0,0,186.74,100.84Zm40.89-26.17a8,8,0,1,0-11.92,10.66,64,64,0,0,1,0,85.34,8,8,0,1,0,11.92,10.66,80,80,0,0,0,0-106.66Z")
    }

    /** Phosphor `speaker-simple-high-fill`. */
    val SpeakerSimpleHighFill: ImageVector by lazy {
        icon("SpeakerSimpleHighFill", 256f, false,
        "M168,32V224a8,8,0,0,1-12.91,6.31L85.25,176H40a16,16,0,0,1-16-16V96A16,16,0,0,1,40,80H85.25l69.84-54.31A8,8,0,0,1,168,32Zm32,64a8,8,0,0,0-8,8v48a8,8,0,0,0,16,0V104A8,8,0,0,0,200,96Zm32-16a8,8,0,0,0-8,8v80a8,8,0,0,0,16,0V88A8,8,0,0,0,232,80Z")
    }

    /** Phosphor `speaker-simple-none-fill`. */
    val SpeakerSimpleNoneFill: ImageVector by lazy {
        icon("SpeakerSimpleNoneFill", 256f, false,
        "M163.52,24.81a8,8,0,0,0-8.43.88L85.25,80H40A16,16,0,0,0,24,96v64a16,16,0,0,0,16,16H85.25l69.84,54.31A7.94,7.94,0,0,0,160,232a8,8,0,0,0,8-8V32A8,8,0,0,0,163.52,24.81Z")
    }

    /** Phosphor `speaker-slash-fill`. */
    val SpeakerSlashFill: ImageVector by lazy {
        icon("SpeakerSlashFill", 256f, false,
        "M213.92,210.62a8,8,0,1,1-11.84,10.76L160,175.09v48.6a8.29,8.29,0,0,1-3.91,7.18,8,8,0,0,1-9-.56l-65.55-51A4,4,0,0,1,80,176.18V87.09L42.08,45.38A8,8,0,1,1,53.92,34.62Zm-27.21-55.46a8,8,0,0,0,11.29-.7,40,40,0,0,0,0-52.88,8,8,0,1,0-12,10.57,24,24,0,0,1,0,31.72A8,8,0,0,0,186.71,155.16Zm40.92-80.49a8,8,0,1,0-11.92,10.66,64,64,0,0,1,0,85.34,8,8,0,1,0,11.92,10.66,80,80,0,0,0,0-106.66ZM153,119.87a4,4,0,0,0,7-2.7V32.25a8.27,8.27,0,0,0-2.88-6.4,8,8,0,0,0-10-.16L103.83,59.33a4,4,0,0,0-.5,5.85ZM60,80H32A16,16,0,0,0,16,96v64a16,16,0,0,0,16,16H60a4,4,0,0,0,4-4V84A4,4,0,0,0,60,80Z")
    }

    /** Phosphor `stop-fill`. */
    val StopFill: ImageVector by lazy {
        icon("StopFill", 256f, false,
        "M216,56V200a16,16,0,0,1-16,16H56a16,16,0,0,1-16-16V56A16,16,0,0,1,56,40H200A16,16,0,0,1,216,56Z")
    }

    /** Phosphor `sun-fill`. */
    val SunFill: ImageVector by lazy {
        icon("SunFill", 256f, false,
        "M120,40V16a8,8,0,0,1,16,0V40a8,8,0,0,1-16,0Zm8,24a64,64,0,1,0,64,64A64.07,64.07,0,0,0,128,64ZM58.34,69.66A8,8,0,0,0,69.66,58.34l-16-16A8,8,0,0,0,42.34,53.66Zm0,116.68-16,16a8,8,0,0,0,11.32,11.32l16-16a8,8,0,0,0-11.32-11.32ZM192,72a8,8,0,0,0,5.66-2.34l16-16a8,8,0,0,0-11.32-11.32l-16,16A8,8,0,0,0,192,72Zm5.66,114.34a8,8,0,0,0-11.32,11.32l16,16a8,8,0,0,0,11.32-11.32ZM48,128a8,8,0,0,0-8-8H16a8,8,0,0,0,0,16H40A8,8,0,0,0,48,128Zm80,80a8,8,0,0,0-8,8v24a8,8,0,0,0,16,0V216A8,8,0,0,0,128,208Zm112-88H216a8,8,0,0,0,0,16h24a8,8,0,0,0,0-16Z")
    }

    /** Phosphor `text-aa`. */
    val TextAa: ImageVector by lazy {
        icon("TextAa", 256f, false,
        "M87.24,52.59a8,8,0,0,0-14.48,0l-64,136a8,8,0,1,0,14.48,6.81L39.9,160h80.2l16.66,35.4a8,8,0,1,0,14.48-6.81ZM47.43,144,80,74.79,112.57,144ZM200,96c-12.76,0-22.73,3.47-29.63,10.32a8,8,0,0,0,11.26,11.36c3.8-3.77,10-5.68,18.37-5.68,13.23,0,24,9,24,20v3.22A42.76,42.76,0,0,0,200,128c-22.06,0-40,16.15-40,36s17.94,36,40,36a42.73,42.73,0,0,0,24-7.25,8,8,0,0,0,16-.75V132C240,112.15,222.06,96,200,96Zm0,88c-13.23,0-24-9-24-20s10.77-20,24-20,24,9,24,20S213.23,184,200,184Z")
    }

    /** Phosphor `text-t`. */
    val TextT: ImageVector by lazy {
        icon("TextT", 256f, false,
        "M208,56V88a8,8,0,0,1-16,0V64H136V192h24a8,8,0,0,1,0,16H96a8,8,0,0,1,0-16h24V64H64V88a8,8,0,0,1-16,0V56a8,8,0,0,1,8-8H200A8,8,0,0,1,208,56Z")
    }

    /** Phosphor `textbox`. */
    val Textbox: ImageVector by lazy {
        icon("Textbox", 256f, false,
        "M112,40a8,8,0,0,0-8,8V64H24A16,16,0,0,0,8,80v96a16,16,0,0,0,16,16h80v16a8,8,0,0,0,16,0V48A8,8,0,0,0,112,40ZM24,176V80h80v96ZM248,80v96a16,16,0,0,1-16,16H144a8,8,0,0,1,0-16h88V80H144a8,8,0,0,1,0-16h88A16,16,0,0,1,248,80ZM88,112a8,8,0,0,1-8,8H72v24a8,8,0,0,1-16,0V120H48a8,8,0,0,1,0-16H80A8,8,0,0,1,88,112Z")
    }

    /** Phosphor `trash`. */
    val Trash: ImageVector by lazy {
        icon("Trash", 256f, false,
        "M216,48H176V40a24,24,0,0,0-24-24H104A24,24,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM96,40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8v8H96Zm96,168H64V64H192ZM112,104v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0v64a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Z")
    }

    /** Phosphor `trash-fill`. */
    val TrashFill: ImageVector by lazy {
        icon("TrashFill", 256f, false,
        "M216,48H176V40a24,24,0,0,0-24-24H104A24,24,0,0,0,80,40v8H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM112,168a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm48,0a8,8,0,0,1-16,0V104a8,8,0,0,1,16,0Zm0-120H96V40a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8Z")
    }

    /** Phosphor `user-circle-fill`. */
    val UserCircleFill: ImageVector by lazy {
        icon("UserCircleFill", 256f, false,
        "M172,120a44,44,0,1,1-44-44A44.05,44.05,0,0,1,172,120Zm60,8A104,104,0,1,1,128,24,104.11,104.11,0,0,1,232,128Zm-16,0a88.09,88.09,0,0,0-91.47-87.93C77.43,41.89,39.87,81.12,40,128.25a87.65,87.65,0,0,0,22.24,58.16A79.71,79.71,0,0,1,84,165.1a4,4,0,0,1,4.83.32,59.83,59.83,0,0,0,78.28,0,4,4,0,0,1,4.83-.32,79.71,79.71,0,0,1,21.79,21.31A87.62,87.62,0,0,0,216,128Z")
    }

    /** Phosphor `user-fill`. */
    val UserFill: ImageVector by lazy {
        icon("UserFill", 256f, false,
        "M230.93,220a8,8,0,0,1-6.93,4H32a8,8,0,0,1-6.92-12c15.23-26.33,38.7-45.21,66.09-54.16a72,72,0,1,1,73.66,0c27.39,8.95,50.86,27.83,66.09,54.16A8,8,0,0,1,230.93,220Z")
    }

    /** Phosphor `users`. */
    val Users: ImageVector by lazy {
        icon("Users", 256f, false,
        "M117.25,157.92a60,60,0,1,0-66.5,0A95.83,95.83,0,0,0,3.53,195.63a8,8,0,1,0,13.4,8.74,80,80,0,0,1,134.14,0,8,8,0,0,0,13.4-8.74A95.83,95.83,0,0,0,117.25,157.92ZM40,108a44,44,0,1,1,44,44A44.05,44.05,0,0,1,40,108Zm210.14,98.7a8,8,0,0,1-11.07-2.33A79.83,79.83,0,0,0,172,168a8,8,0,0,1,0-16,44,44,0,1,0-16.34-84.87,8,8,0,1,1-5.94-14.85,60,60,0,0,1,55.53,105.64,95.83,95.83,0,0,1,47.22,37.71A8,8,0,0,1,250.14,206.7Z")
    }

    /** Phosphor `users-fill`. */
    val UsersFill: ImageVector by lazy {
        icon("UsersFill", 256f, false,
        "M164.47,195.63a8,8,0,0,1-6.7,12.37H10.23a8,8,0,0,1-6.7-12.37,95.83,95.83,0,0,1,47.22-37.71,60,60,0,1,1,66.5,0A95.83,95.83,0,0,1,164.47,195.63Zm87.91-.15a95.87,95.87,0,0,0-47.13-37.56A60,60,0,0,0,144.7,54.59a4,4,0,0,0-1.33,6A75.83,75.83,0,0,1,147,150.53a4,4,0,0,0,1.07,5.53,112.32,112.32,0,0,1,29.85,30.83,23.92,23.92,0,0,1,3.65,16.47,4,4,0,0,0,3.95,4.64h60.3a8,8,0,0,0,7.73-5.93A8.22,8.22,0,0,0,252.38,195.48Z")
    }

    /** Phosphor `video-camera-fill`. */
    val VideoCameraFill: ImageVector by lazy {
        icon("VideoCameraFill", 256f, false,
        "M192,72V184a16,16,0,0,1-16,16H32a16,16,0,0,1-16-16V72A16,16,0,0,1,32,56H176A16,16,0,0,1,192,72Zm58,.25a8.23,8.23,0,0,0-6.63,1.22L209.78,95.86A4,4,0,0,0,208,99.19v57.62a4,4,0,0,0,1.78,3.33l33.78,22.52a8,8,0,0,0,8.58.19,8.33,8.33,0,0,0,3.86-7.17V80A8,8,0,0,0,250,72.25Z")
    }

    /** Phosphor `video-camera-slash-fill`. */
    val VideoCameraSlashFill: ImageVector by lazy {
        icon("VideoCameraSlashFill", 256f, false,
        "M256,80.23v95.45a8.33,8.33,0,0,1-3.86,7.17,8,8,0,0,1-8.58-.19l-33.78-22.52a4,4,0,0,1-1.78-3.33V99.19a4,4,0,0,1,1.78-3.32l33.78-22.53a8,8,0,0,1,9.73.66A8.23,8.23,0,0,1,256,80.23ZM53.92,34.62A8,8,0,1,0,42.08,45.38L51.73,56H32A16,16,0,0,0,16,72V184a16,16,0,0,0,16,16H182.64l19.44,21.38a8,8,0,1,0,11.84-10.76ZM185,155.07a4,4,0,0,0,7-2.7V72a16,16,0,0,0-16-16H104a4,4,0,0,0-3,6.69Z")
    }

    /** Phosphor `warning-circle-fill`. */
    val WarningCircleFill: ImageVector by lazy {
        icon("WarningCircleFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm-8,56a8,8,0,0,1,16,0v56a8,8,0,0,1-16,0Zm8,104a12,12,0,1,1,12-12A12,12,0,0,1,128,184Z")
    }

    /** Phosphor `warning-fill`. */
    val WarningFill: ImageVector by lazy {
        icon("WarningFill", 256f, false,
        "M236.8,188.09,149.35,36.22h0a24.76,24.76,0,0,0-42.7,0L19.2,188.09a23.51,23.51,0,0,0,0,23.72A24.35,24.35,0,0,0,40.55,224h174.9a24.35,24.35,0,0,0,21.33-12.19A23.51,23.51,0,0,0,236.8,188.09ZM120,104a8,8,0,0,1,16,0v40a8,8,0,0,1-16,0Zm8,88a12,12,0,1,1,12-12A12,12,0,0,1,128,192Z")
    }

    /** Phosphor `waveform`. */
    val Waveform: ImageVector by lazy {
        icon("Waveform", 256f, false,
        "M56,96v64a8,8,0,0,1-16,0V96a8,8,0,0,1,16,0ZM88,24a8,8,0,0,0-8,8V224a8,8,0,0,0,16,0V32A8,8,0,0,0,88,24Zm40,32a8,8,0,0,0-8,8V192a8,8,0,0,0,16,0V64A8,8,0,0,0,128,56Zm40,32a8,8,0,0,0-8,8v64a8,8,0,0,0,16,0V96A8,8,0,0,0,168,88Zm40-16a8,8,0,0,0-8,8v96a8,8,0,0,0,16,0V80A8,8,0,0,0,208,72Z")
    }

    /** Phosphor `wifi-slash`. */
    val WifiSlash: ImageVector by lazy {
        icon("WifiSlash", 256f, false,
        "M213.92,210.62a8,8,0,1,1-11.84,10.76l-52-57.15a60,60,0,0,0-57.41,7.24,8,8,0,1,1-9.42-12.93A75.43,75.43,0,0,1,128,144c1.28,0,2.55,0,3.82.1L104.9,114.49A108,108,0,0,0,61,135.31,8,8,0,0,1,49.73,134,8,8,0,0,1,51,122.77a124.27,124.27,0,0,1,41.71-21.66L69.37,75.4a155.43,155.43,0,0,0-40.29,24A8,8,0,0,1,18.92,87,171.87,171.87,0,0,1,58,62.86L42.08,45.38A8,8,0,1,1,53.92,34.62ZM128,192a12,12,0,1,0,12,12A12,12,0,0,0,128,192ZM237.08,87A172.3,172.3,0,0,0,106,49.4a8,8,0,1,0,2,15.87A158.33,158.33,0,0,1,128,64a156.25,156.25,0,0,1,98.92,35.37A8,8,0,0,0,237.08,87ZM195,135.31a8,8,0,0,0,11.24-1.3,8,8,0,0,0-1.3-11.24,124.25,124.25,0,0,0-51.73-24.2A8,8,0,1,0,150,114.24,108.12,108.12,0,0,1,195,135.31Z")
    }

    /** Phosphor `x-bold`. */
    val XBold: ImageVector by lazy {
        icon("XBold", 256f, false,
        "M208.49,191.51a12,12,0,0,1-17,17L128,145,64.49,208.49a12,12,0,0,1-17-17L111,128,47.51,64.49a12,12,0,0,1,17-17L128,111l63.51-63.52a12,12,0,0,1,17,17L145,128Z")
    }

    /** Phosphor `x-circle-fill`. */
    val XCircleFill: ImageVector by lazy {
        icon("XCircleFill", 256f, false,
        "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm37.66,130.34a8,8,0,0,1-11.32,11.32L128,139.31l-26.34,26.35a8,8,0,0,1-11.32-11.32L116.69,128,90.34,101.66a8,8,0,0,1,11.32-11.32L128,116.69l26.34-26.35a8,8,0,0,1,11.32,11.32L139.31,128Z")
    }
}

private fun icon(name: String, viewport: Float, stroked: Boolean, vararg paths: String): ImageVector =
    ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = viewport,
        viewportHeight = viewport,
    ).apply {
        for (data in paths) {
            if (stroked) {
                addPath(
                    pathData = addPathNodes(data),
                    stroke = SolidColor(Color.Black),
                    strokeLineWidth = 2f,
                    strokeLineCap = StrokeCap.Round,
                    strokeLineJoin = StrokeJoin.Round,
                )
            } else {
                addPath(pathData = addPathNodes(data), fill = SolidColor(Color.Black))
            }
        }
    }.build()
