import SwiftUI

/// One third-party component that ships in the app (or that it downloads, like the Whisper model).
///
/// Human: `OpenSourceLicenses.json` is generated by `ios/scripts/generate-licenses.py` from
/// Package.resolved, the packages' own LICENSE/NOTICE files and a short table for the rest. Re-run
/// it when a dependency changes; never edit the JSON by hand.
nonisolated struct OpenSourceLicense: Decodable, Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let version: String
    /// SPDX identifier, e.g. `MIT`, `Apache-2.0`.
    let license: String
    let url: String
    /// The full license (and notice) text.
    let text: String

    /// The bundled list, sorted by name; empty if the resource is missing or unreadable.
    static let bundled: [OpenSourceLicense] = load(from: .main)

    static func load(from bundle: Bundle) -> [OpenSourceLicense] {
        guard let url = bundle.url(forResource: "OpenSourceLicenses", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let list = try? JSONDecoder().decode([OpenSourceLicense].self, from: data)
        else { return [] }
        return list
    }

    /// "0.18.0 · MIT", the list row's subtitle.
    var summary: String {
        "\(version) · \(license)"
    }
}

/// Settings → About Shroud → Open-Source Licenses: every third-party component, A–Z.
///
/// Agent: READS `OpenSourceLicense.bundled`; pushes `.license(id)`.
struct OpenSourceLicensesView: View {
    @Binding var navigationPath: [SettingsRoute]

    @ScaledMetric(relativeTo: .body) private var titleSize: CGFloat = 16
    @ScaledMetric(relativeTo: .footnote) private var subtitleSize: CGFloat = 13
    @ScaledMetric(relativeTo: .subheadline) private var introSize: CGFloat = 14

    private let licenses = OpenSourceLicense.bundled

    var body: some View {
        GroupedScreen {
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    Text("Shroud is built with these open-source components. Tap one to read its license.")
                        .font(.system(size: introSize))
                        .foregroundStyle(Theme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.horizontal, 14)
                        .padding(.top, 4)

                    VStack(spacing: 0) {
                        ForEach(Array(licenses.enumerated()), id: \.element.id) { index, item in
                            if index > 0 {
                                Rectangle()
                                    .fill(Theme.separator)
                                    .frame(height: 1)
                                    .padding(.leading, 14)
                            }
                            row(item)
                        }
                    }
                    .background(Theme.background)
                    .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))

                    Color.clear.frame(height: 24)
                }
                .padding(.horizontal, 16)
                .padding(.top, 8)
            }
        }
        .navigationTitle("Open-Source Licenses")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.visible, for: .navigationBar)
    }

    private func row(_ item: OpenSourceLicense) -> some View {
        Button {
            navigationPath.append(.license(item.id))
        } label: {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 2) {
                    Text(item.name)
                        .font(.system(size: titleSize))
                        .foregroundStyle(Theme.textPrimary)
                    Text(item.summary)
                        .font(.system(size: subtitleSize))
                        .foregroundStyle(Theme.textSecondary)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                Image(systemName: "chevron.right")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(Theme.chevron)
                    .accessibilityHidden(true)
            }
            .padding(.horizontal, 14)
            .padding(.vertical, 10)
            .contentShape(Rectangle())
        }
        .buttonStyle(HighlightRowButtonStyle())
        .accessibilityLabel("\(item.name), version \(item.version), \(item.license)")
    }
}

/// One component's license text, selectable so it can be copied.
struct OpenSourceLicenseDetailView: View {
    let licenseID: String

    @Environment(\.openURL) private var openURL

    @ScaledMetric(relativeTo: .headline) private var nameSize: CGFloat = 17
    @ScaledMetric(relativeTo: .footnote) private var subtitleSize: CGFloat = 13
    @ScaledMetric(relativeTo: .subheadline) private var linkSize: CGFloat = 15
    @ScaledMetric(relativeTo: .caption) private var textSize: CGFloat = 12

    private var item: OpenSourceLicense? {
        OpenSourceLicense.bundled.first { $0.id == licenseID }
    }

    var body: some View {
        GroupedScreen {
            ScrollView {
                if let item {
                    VStack(alignment: .leading, spacing: 14) {
                        summaryCard(item)
                        Text(item.text)
                            .font(.system(size: textSize, design: .monospaced))
                            .foregroundStyle(Theme.textPrimary)
                            .textSelection(.enabled)
                            .fixedSize(horizontal: false, vertical: true)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(14)
                            .background(Theme.background)
                            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
                        Color.clear.frame(height: 24)
                    }
                    .padding(.horizontal, 16)
                    .padding(.top, 8)
                }
            }
        }
        .navigationTitle(item?.name ?? "License")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.visible, for: .navigationBar)
    }

    private func summaryCard(_ item: OpenSourceLicense) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(item.name)
                .font(.system(size: nameSize, weight: .semibold))
                .foregroundStyle(Theme.textPrimary)
                .accessibilityAddTraits(.isHeader)
            Text(item.summary)
                .font(.system(size: subtitleSize))
                .foregroundStyle(Theme.textSecondary)
            if let url = URL(string: item.url) {
                Button {
                    openURL(url)
                } label: {
                    Text(item.url.replacingOccurrences(of: "https://", with: ""))
                        // A 44 pt target without moving the text; the slop stays inside the card.
                        .contentShape(Rectangle().inset(by: -13))
                }
                .font(.system(size: linkSize, weight: .semibold))
                .foregroundStyle(Theme.accentText)
                .padding(.top, 6)
                .accessibilityAddTraits(.isLink)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(14)
        .background(Theme.background)
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
    }
}

#Preview("List") {
    NavigationStack {
        OpenSourceLicensesView(navigationPath: .constant([]))
    }
}

#Preview("Detail") {
    NavigationStack {
        OpenSourceLicenseDetailView(licenseID: "whisperkit")
    }
}
