package de.corespace.shroud.core.messaging.reactions

import com.ibm.icu.util.VersionInfo
import de.corespace.shroud.core.net.wire.Icu4jTextUnitsRule
import de.corespace.shroud.core.net.wire.MessageReactionPayload
import de.corespace.shroud.core.net.wire.TextUnits
import de.corespace.shroud.core.net.wire.UnicodeVersionTextUnits
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Rule
import org.junit.Test
import java.io.File
import java.util.concurrent.TimeUnit

/**
 * The Kotlin reaction table is generated by `scripts/gen_reaction_set.py` next to the Swift and TS
 * ones (plan §4 R1, messaging-core §19.9). This pins that the three are the same table — 375 emoji,
 * same order, same keywords — by reading `ios/shroud/Services/Messaging/ReactionSet.swift` and
 * `web/src/reactionSet.ts` from the repository, and runs the generator's `--check` when a Python new
 * enough for its Unicode names is installed.
 */
class ReactionSetTest {
    @get:Rule
    val textUnits = Icu4jTextUnitsRule()

    private val repoRoot: File by lazy {
        generateSequence(File(System.getProperty("user.dir")).absoluteFile) { it.parentFile }
            .firstOrNull { File(it, SWIFT_TABLE).isFile && File(it, GENERATOR).isFile }
            ?: error("repository root (with $SWIFT_TABLE) not found above ${System.getProperty("user.dir")}")
    }

    @Test
    fun theSetHas375EmojiQuickSevenFirst() {
        assertEquals(375, ReactionSet.all.size)
        assertEquals(listOf("❤️", "🔥", "👍", "😢", "🙏", "😮", "👎"), ReactionSet.quick)
        assertEquals(ReactionSet.quick, ReactionSet.all.take(7))
        assertEquals(ReactionSet.all.size, ReactionSet.all.toSet().size)
        assertEquals(ReactionSet.all, ReactionSet.keywords.keys.toList())
    }

    @Test
    fun kotlinTableEqualsTheSwiftTable() {
        val swift = File(repoRoot, SWIFT_TABLE).readLines()
        val quick = swift.single { "static let quick" in it }
        assertEquals(ReactionSet.quick, literals(quick))

        val allStart = swift.indexOfFirst { "static let all" in it }
        val allEnd = swift.indexOfFirst(allStart) { it.trim() == "]" }
        assertEquals(ReactionSet.all, swift.subList(allStart + 1, allEnd).flatMap(::literals))

        val keywordsStart = swift.indexOfFirst { "static let keywords" in it }
        val keywordsEnd = swift.indexOfFirst(keywordsStart) { it.trim() == "]" }
        val swiftKeywords = swift.subList(keywordsStart + 1, keywordsEnd).map { line ->
            val strings = literals(line)
            strings.first() to strings.drop(1)
        }
        assertEquals(375, swiftKeywords.size)
        assertEquals(ReactionSet.keywords.toList(), swiftKeywords)
    }

    @Test
    fun kotlinTableEqualsTheWebTable() {
        val ts = File(repoRoot, TS_TABLE).readLines()
        assertEquals(ReactionSet.quick, literals(ts.single { "export const QUICK_REACTIONS" in it }))
        val allStart = ts.indexOfFirst { "export const ALL_REACTIONS" in it }
        val allEnd = ts.indexOfFirst(allStart) { it.trim() == "];" }
        assertEquals(ReactionSet.all, ts.subList(allStart + 1, allEnd).flatMap(::literals))
        val keywordsStart = ts.indexOfFirst { "export const REACTION_KEYWORDS" in it }
        val keywordsEnd = ts.indexOfFirst(keywordsStart) { it.trim() == "};" }
        val tsKeywords = ts.subList(keywordsStart + 1, keywordsEnd).map { line ->
            val strings = literals(line)
            strings.first() to strings.drop(1)
        }
        assertEquals(ReactionSet.keywords.toList(), tsKeywords)
    }

    /**
     * Every emoji the picker offers passes the reader's own rule (`MessageReactionPayload.isSingleEmoji`),
     * on today's ICU and on API 30's (Unicode 13, simulated) — so a pick is never dropped by the
     * reader that shows it. `MessageReactionPayloadDeviceTest` checks the real API 30 ICU.
     */
    @Test
    fun everyPickableEmojiIsASingleEmojiOnEveryIcu() {
        for (emoji in ReactionSet.all) assertTrue(emoji, MessageReactionPayload.isSingleEmoji(emoji))
        val previous = TextUnits.current
        TextUnits.current = UnicodeVersionTextUnits(VersionInfo.getInstance(13, 0))
        try {
            for (emoji in ReactionSet.all) assertTrue("$emoji on Unicode 13", MessageReactionPayload.isSingleEmoji(emoji))
        } finally {
            TextUnits.current = previous
        }
    }

    /**
     * `python3 scripts/gen_reaction_set.py --check` regenerates the three tables in memory and fails
     * when one differs. The emoji names come from Python's `unicodedata`, which needs Python 3.13+
     * (Unicode 15.1+); with no such Python on the machine the test is skipped (CI runs the check as
     * its own step).
     */
    @Test
    fun generatorCheckReportsTheTablesInStep() {
        val python = listOf("python3.14", "python3.13", "python3").firstOrNull(::isPython313OrNewer)
        assumeTrue("no Python 3.13+ to run the generator with", python != null)
        val process = ProcessBuilder(checkNotNull(python), GENERATOR, "--check")
            .directory(repoRoot)
            .redirectErrorStream(true)
            .start()
        val output = process.inputStream.bufferedReader().readText()
        assertTrue("generator timed out", process.waitFor(60, TimeUnit.SECONDS))
        assertEquals(output, 0, process.exitValue())
        assertTrue(output, output.contains("375 emoji"))
    }

    // ---------------------------------------------------------------------------------------------

    /** The string literals of one generated line. The generator escapes nothing in these tables. */
    private fun literals(line: String): List<String> = STRING.findAll(line).map { it.groupValues[1] }.toList()

    private fun List<String>.indexOfFirst(from: Int, predicate: (String) -> Boolean): Int =
        (from until size).first { predicate(this[it]) }

    private fun isPython313OrNewer(command: String): Boolean = try {
        val process = ProcessBuilder(command, "-c", "import sys; print(sys.version_info >= (3, 13))")
            .redirectErrorStream(true)
            .start()
        val output = process.inputStream.bufferedReader().readText().trim()
        process.waitFor(10, TimeUnit.SECONDS) && process.exitValue() == 0 && output == "True"
    } catch (_: java.io.IOException) {
        false
    }

    private companion object {
        const val SWIFT_TABLE = "ios/shroud/Services/Messaging/ReactionSet.swift"
        const val TS_TABLE = "web/src/reactionSet.ts"
        const val GENERATOR = "scripts/gen_reaction_set.py"
        val STRING = Regex("\"((?:[^\"\\\\]|\\\\.)*)\"")
    }
}
