import Foundation
import Testing
@testable import shroud

/// The bundled list behind Settings › About Shroud › Open-Source Licenses
/// (generated by `ios/scripts/generate-licenses.py`).
struct OpenSourceLicenseTests {
    private let licenses = OpenSourceLicense.bundled

    @Test func theListShipsInTheApp() {
        #expect(!licenses.isEmpty, "OpenSourceLicenses.json is missing from the app's resources")
    }

    @Test func everyEntryIsComplete() {
        for item in licenses {
            #expect(!item.name.isEmpty)
            #expect(!item.version.isEmpty, "\(item.id) has no version")
            #expect(!item.license.isEmpty, "\(item.id) has no license id")
            #expect(item.text.count > 500, "\(item.id) has no license text")
            #expect(URL(string: item.url)?.scheme == "https", "\(item.id) links to \(item.url)")
        }
        #expect(Set(licenses.map(\.id)).count == licenses.count, "ids are unique")
    }

    @Test func listsWhatShipsAndNothingThatDoesnt() {
        let ids = Set(licenses.map(\.id))
        let packages = ["whisperkit", "swift-transformers", "swift-jinja", "swift-collections", "swift-crypto", "yyjson"]
        // WebRTC.xcframework and the libraries linked into it.
        let webRTC = ["webrtc", "abseil", "boringssl", "dav1d", "libaom", "libcxx", "libsrtp", "libvpx", "libyuv", "opus", "protobuf"]
        for shipped in packages + webRTC + ["bip39-wordlist", "whisper-model"] {
            #expect(ids.contains(shipped), "\(shipped) is missing")
        }
        // Resolved, but only WhisperKit's CLI and swift-crypto's CryptoExtras link them.
        #expect(!ids.contains("swift-argument-parser"))
        #expect(!ids.contains("swift-asn1"))
    }

    @Test func sortedByName() {
        let names = licenses.map { $0.name.lowercased() }
        #expect(names == names.sorted())
    }

    @Test func apacheNoticesComeAlong() throws {
        let crypto = try #require(licenses.first { $0.id == "swift-crypto" })
        #expect(crypto.license == "Apache-2.0")
        #expect(crypto.text.contains("The SwiftCrypto Project"))
    }
}
